package com.redhat.mercury.customercreditrating.camel;

import javax.annotation.Generated;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.rest.RestParamType;

/**
 * Generated from OpenApi specification by Camel REST DSL generator.
 */
@Generated("org.apache.camel.generator.openapi.PathGenerator")
public final class CustomerCreditRatingRoute extends RouteBuilder {
    /**
     * Defines Apache Camel routes using REST DSL fluent API.
     */
    public void configure() {
        rest()
            .post("/customer-credit-rating/activation")
                .id("activateSDCustomerCreditRating")
                .description("Activate  a  SDCustomerCreditRating servicing session")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("SDCustomerCreditRating Request Payload")
                .endParam()
                .to("direct:activateSDCustomerCreditRating")
            .put("/customer-credit-rating/{sdReferenceId}/configuration")
                .id("configureSDCustomerCreditRating")
                .description("Update an active SDCustomerCreditRating session configuration")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("SDCustomerCreditRating Servicing Session Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("SDCustomerCreditRating Configure Request Payload")
                .endParam()
                .to("direct:configureSDCustomerCreditRating")
            .put("/customer-credit-rating/{sdReferenceId}/feedback")
                .id("feedbackSDCustomerCreditRating")
                .description("Capturing feedback against the SDCustomerCreditRating service that can target different levels of detail: SD/CR/BQ")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("SDCustomerCreditRating Servicing Session Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("SDCustomerCreditRating Feedback Request Payload")
                .endParam()
                .to("direct:feedbackSDCustomerCreditRating")
            .get("/customer-credit-rating/{sdReferenceId}")
                .id("retrieveSDCustomerCreditRating")
                .description("Analytical views maintained by the SDCustomerCreditRating service center for management reporting and analysis purposes")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("SDCustomerCreditRating Servicing Session Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/SDCustomerCreditRatingRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveSDCustomerCreditRating")
            .post("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/initiation")
                .id("initiateCustomerCreditRatingState")
                .description("Initiate credit state monitoring for a customer")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("CustomerCreditRatingState Request Payload")
                .endParam()
                .to("direct:initiateCustomerCreditRatingState")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/control")
                .id("controlCustomerCreditRatingStateUpdate")
                .description("Control credit state monitoring (e.g. high frequency update)")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Credit Rating State Request Payload")
                .endParam()
                .to("direct:controlCustomerCreditRatingStateUpdate")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/exchange")
                .id("exchangeCustomerCreditRatingStateUpdate")
                .description("Accept, reject, etc credit state monitoring content")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Credit Rating State Request Payload")
                .endParam()
                .to("direct:exchangeCustomerCreditRatingStateUpdate")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/execution")
                .id("executeCustomerCreditRatingStateUpdate")
                .description("Execute an automated task for credit state (e.g. auto refresh)")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Credit Rating State Request Payload")
                .endParam()
                .to("direct:executeCustomerCreditRatingStateUpdate")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/requisition")
                .id("requestCustomerCreditRatingStateUpdate")
                .description("Request manual intervention for credit state (e.g. revise underlying assessment)")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Credit Rating State Request Payload")
                .endParam()
                .to("direct:requestCustomerCreditRatingStateUpdate")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}")
                .id("retrieveCustomerCreditRating")
                .description("Retrieve details about credit state monitoring for a customer")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/CRCustomerCreditRatingStateRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerCreditRating")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/alerts/{bqReferenceId}/capture")
                .id("captureCustomerCreditRatingStateAlertsUpdate")
                .description("Capture notification of a credit alert")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Alerts Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Alerts request payload")
                .endParam()
                .to("direct:captureCustomerCreditRatingStateAlertsUpdate")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/alerts/{bqReferenceId}/")
                .id("retrieveCustomerCreditRatingStateAlerts")
                .description("Retrieve details about a credit alert .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Alerts Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQAlertsRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerCreditRatingStateAlerts")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/internalreporting/{bqReferenceId}/")
                .id("retrieveCustomerCreditRatingStateInternalReporting")
                .description("Retrieve details about internal reporting to the credit monitoring activity .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("InternalReporting Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQInternalReportingRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerCreditRatingStateInternalReporting")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/externalreporting/{bqReferenceId}/capture")
                .id("captureCustomerCreditRatingStateExternalReportingUpdate")
                .description("Capture external credit reports to support credit analysis and state")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("ExternalReporting Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("ExternalReporting request payload")
                .endParam()
                .to("direct:captureCustomerCreditRatingStateExternalReportingUpdate")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/externalreporting/{bqReferenceId}/")
                .id("retrieveCustomerCreditRatingStateExternalReporting")
                .description("Retrieve details about external reporting to the credit monitoring activity .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("ExternalReporting Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQExternalReportingRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerCreditRatingStateExternalReporting")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state")
                .id("RetrieveCustomerCreditRatingReferenceIds")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("collection-filter")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Filter to refine the result set. ex- CustomerCreditRating Instance Status='active'")
                .endParam()
                .to("direct:RetrieveCustomerCreditRatingReferenceIds")
            .get("/customer-credit-rating/customer-credit-rating-state/behavior-qualifiers/")
                .id("RetrieveCustomerCreditRatingBehaviorQualifiers")
                .produces("application/json")
                .to("direct:RetrieveCustomerCreditRatingBehaviorQualifiers")
            .get("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/{behaviorQualifier}/")
                .id("RetrieveCustomerCreditRatingBehaviorQualifierReferenceIds")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("behaviorQualifier")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Behavior Qualifier Name. ex- ExternalReporting")
                .endParam()
                .param()
                    .name("collection-filter")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Filter to refine the result set. ex- ExternalReporting Instance Status = 'pending'")
                .endParam()
                .to("direct:RetrieveCustomerCreditRatingBehaviorQualifierReferenceIds")
            .put("/customer-credit-rating/{sdReferenceId}/customer-credit-rating-state/{crReferenceId}/internalreporting/{bqReferenceId}/capture")
                .id("captureCustomerCreditRatingStateInternalReportingUpdate")
                .description("Capture internal product reports to support credit analysis")
                .consumes("*/*")
                .produces("application/json")
                .param()
                    .name("sdReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating Servicing Session Reference")
                .endParam()
                .param()
                    .name("crReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Credit Rating State Instance Reference")
                .endParam()
                .param()
                    .name("bqReferenceId")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("InternalReporting Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("InternalReporting request payload")
                .endParam()
                .to("direct:captureCustomerCreditRatingStateInternalReportingUpdate");
    }
}
