apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  name: camel-k
spec:
  build:
    maven:
      properties:
        repo.url: https://maven.pkg.github.com/open-accelerators/mercury
      settings:
        configMapKeyRef:
          key: settings.xml
          name: mercury-mvn-settings