package com.redhat.productdeployment;

import javax.annotation.Generated;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.builder.TransformerBuilder;
import org.apache.camel.component.servlet.CamelHttpTransportServlet;
import org.apache.camel.model.rest.RestBindingMode;
import org.apache.camel.model.rest.RestParamType;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

import java.net.InetAddress;
import java.net.UnknownHostException;

/**
 * Generated from Swagger specification by Camel REST DSL generator.
 */
@Component
@Generated("org.apache.camel.generator.swagger.PathGenerator")
public final class CamelRoutes extends RouteBuilder {
    /**
     * Defines Apache Camel routes using REST DSL fluent API.
     */

    @Value("${oc.project.path}")
    String projectPath;

    @Bean
    public ServletRegistrationBean servletRegistrationBean() {
        ServletRegistrationBean registration = new ServletRegistrationBean(new CamelHttpTransportServlet(), "/service/*");
        registration.setName("CamelServlet");
        return registration;
    }
    public void configure() throws UnknownHostException {

        restConfiguration()
                .component("servlet")

                .bindingMode(RestBindingMode.auto)
                .producerComponent("http4")
                .apiContextPath("/swagger") //swagger endpoint path
                .apiContextRouteId("swagger") //id of route providing the swagger endpoint

                //Swagger properties
                .contextPath("/service")
                .host(projectPath)
                .apiProperty("api.title", "Example REST api")
                .apiProperty("api.version", "1.0");

        rest()
            .post("/product-deployment/activation")
                .id("activateSDProductDeployment")
                .description("Activate  a  SDProductDeployment servicing session")
                .produces("application/json")
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("SDProductDeployment Request Payload")
                .endParam()
                .to("direct:activateSDProductDeployment")
            .put("/product-deployment/{sd-reference-id}/configuration")
                .id("configureSDProductDeployment")
                .description("Update an active SDProductDeployment session configuration")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("SDProductDeployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("SDProductDeployment Configure Request Payload")
                .endParam()
                .to("direct:configureSDProductDeployment")
            .put("/product-deployment/{sd-reference-id}/feedback")
                .id("feedbackSDProductDeployment")
                .description("Capturing feedback against the SDProductDeployment service that can target different levels of detail: SD/CR/BQ")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("SDProductDeployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("SDProductDeployment Feedback Request Payload")
                .endParam()
                .to("direct:feedbackSDProductDeployment")
            .get("/product-deployment/{sd-reference-id}")
                .id("retrieveSDProductDeployment")
                .description("Analytical views maintained by the SDProductDeployment service center for management reporting and analysis purposes")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("SDProductDeployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/SDProductDeploymentRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveSDProductDeployment")
            .post("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/creation")
                .id("createProductOrServiceDeploymentProject")
                .description("Create a product or service deployment project")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("ProductOrServiceDeploymentProject Request Payload")
                .endParam()
                .to("direct:createProductOrServiceDeploymentProject")
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/update")
                .id("updateProductOrServiceDeploymentProject")
                .description("Update details of a product or service deployment project")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Product Or Service Deployment Project Request Payload")
                .endParam()
                .to("direct:updateProductOrServiceDeploymentProject")
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/control")
                .id("controlProductOrServiceDeploymentProjectUpdate")
                .description("Control the execution of a product or service deployment project (e.g. suspend)")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Product Or Service Deployment Project Request Payload")
                .endParam()
                .to("direct:controlProductOrServiceDeploymentProjectUpdate")
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/exchange")
                .id("exchangeProductOrServiceDeploymentProjectUpdate")
                .description("Accept, verify etc. aspects of a product or service deployment project")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Product Or Service Deployment Project Request Payload")
                .endParam()
                .to("direct:exchangeProductOrServiceDeploymentProjectUpdate")
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/capture")
                .id("captureProductOrServiceDeploymentProjectUpdate")
                .description("Capture details about tasks performed during the deployment")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Product Or Service Deployment Project Request Payload")
                .endParam()
                .to("direct:captureProductOrServiceDeploymentProjectUpdate")
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/requisition")
                .id("requestProductOrServiceDeploymentProjectUpdate")
                .description("Request manual intervention in a deployment project")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Product Or Service Deployment Project Request Payload")
                .endParam()
                .to("direct:requestProductOrServiceDeploymentProjectUpdate")
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/grant")
                .id("grantProductOrServiceDeploymentProjectUpdate")
                .description("Grant permission to perform some action or access resources under the control of the deployment")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Product Or Service Deployment Project Request Payload")
                .endParam()
                .to("direct:grantProductOrServiceDeploymentProjectUpdate")
            .get("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}")
                .id("retrieveProductDeployment")
                .description("Retrieve details about a deployment project")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/CRProductOrServiceDeploymentProjectRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveProductDeployment")
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/systems/{bq-reference-id}/update")
                .id("updateProductOrServiceDeploymentProjectSystems")
                .description("Update details relating to the systems tasks of the deployment")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Systems Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Systems Request Payload")
                .endParam()
                .to("direct:updateProductOrServiceDeploymentProjectSystems");
        rest()
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/systems/{bq-reference-id}/exchange")
                .id("exchangeProductOrServiceDeploymentProjectSystemsUpdate")
                .description("Accept, reject etc. a systems related task of the deployment")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Systems Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Systems request payload")
                .endParam()
                .to("direct:exchangeProductOrServiceDeploymentProjectSystemsUpdate")
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/systems/{bq-reference-id}/requisition")
                .id("requestProductOrServiceDeploymentProjectSystemsUpdate")
                .description("Request manual intervention in a systems related deployment task")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Systems Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Systems request payload")
                .endParam()
                .to("direct:requestProductOrServiceDeploymentProjectSystemsUpdate");
        rest()
            .get("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/systems/{bq-reference-id}/")
                .id("retrieveProductOrServiceDeploymentProjectSystems")
                .description("Retrieve details about a systems related deployment task or deliverable .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Systems Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQSystemsRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveProductOrServiceDeploymentProjectSystems")
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/itoperations/{bq-reference-id}/update")
                .id("updateProductOrServiceDeploymentProjectITOperations")
                .description("Update details relating to the IT operations tasks of the deployment")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("ITOperations Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("ITOperations Request Payload")
                .endParam()
                .to("direct:updateProductOrServiceDeploymentProjectITOperations");
        rest()
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/itoperations/{bq-reference-id}/exchange")
                .id("exchangeProductOrServiceDeploymentProjectITOperationsUpdate")
                .description("Accept, reject etc. an IT operations related task of the deployment")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("ITOperations Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("ITOperations request payload")
                .endParam()
                .to("direct:exchangeProductOrServiceDeploymentProjectITOperationsUpdate")
            .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/itoperations/{bq-reference-id}/requisition")
                .id("requestProductOrServiceDeploymentProjectITOperationsUpdate")
                .description("Request manual intervention in an IT operations related deployment task")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("ITOperations Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("ITOperations request payload")
                .endParam()
                .to("direct:requestProductOrServiceDeploymentProjectITOperationsUpdate")
            .get("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/itoperations/{bq-reference-id}/")
                .id("retrieveProductOrServiceDeploymentProjectITOperations")
                .description("Retrieve details about an IT operations related deployment task or deliverable .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("ITOperations Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQITOperationsRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveProductOrServiceDeploymentProjectITOperations")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/hroperations/{bq-reference-id}/update")
                .id("updateProductOrServiceDeploymentProjectHROperations")
                .description("Update details relating to the staff operations tasks of the deployment")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("HROperations Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("HROperations Request Payload")
                .endParam()
                .to("direct:updateProductOrServiceDeploymentProjectHROperations");
        rest()

                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/hroperations/{bq-reference-id}/exchange")
                .id("exchangeProductOrServiceDeploymentProjectHROperationsUpdate")
                .description("Accept, reject etc. a staff operations related task of the deployment")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("HROperations Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("HROperations request payload")
                .endParam()
                .to("direct:exchangeProductOrServiceDeploymentProjectHROperationsUpdate")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/hroperations/{bq-reference-id}/requisition")
                .id("requestProductOrServiceDeploymentProjectHROperationsUpdate")
                .description("Request manual intervention in a staff operations related deployment task")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("HROperations Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("HROperations request payload")
                .endParam()
                .to("direct:requestProductOrServiceDeploymentProjectHROperationsUpdate")
                .get("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/hroperations/{bq-reference-id}/")
                .id("retrieveProductOrServiceDeploymentProjectHROperations")
                .description("Retrieve details about a staff operations related deployment task or deliverable .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("HROperations Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQHROperationsRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveProductOrServiceDeploymentProjectHROperations");

        rest()

                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/salesandmarketing/{bq-reference-id}/update")
                .id("updateProductOrServiceDeploymentProjectSalesandMarketing")
                .description("Update details relating to the sales and marketing tasks of the deployment")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("SalesandMarketing Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("SalesandMarketing Request Payload")
                .endParam()
                .to("direct:updateProductOrServiceDeploymentProjectSalesandMarketing")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/salesandmarketing/{bq-reference-id}/exchange")
                .id("exchangeProductOrServiceDeploymentProjectSalesandMarketingUpdate")
                .description("Accept, reject etc. a sales and marketing related task of the deployment")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("SalesandMarketing Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("SalesandMarketing request payload")
                .endParam()
                .to("direct:exchangeProductOrServiceDeploymentProjectSalesandMarketingUpdate")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/salesandmarketing/{bq-reference-id}/requisition")
                .id("requestProductOrServiceDeploymentProjectSalesandMarketingUpdate")
                .description("Request manual intervention in a sales and marketing related deployment task")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("SalesandMarketing Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("SalesandMarketing request payload")
                .endParam()
                .to("direct:requestProductOrServiceDeploymentProjectSalesandMarketingUpdate")
                .get("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/salesandmarketing/{bq-reference-id}/")
                .id("retrieveProductOrServiceDeploymentProjectSalesandMarketing")
                .description("Retrieve details about a sales and marketing related deployment task or deliverable .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("SalesandMarketing Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQSalesandMarketingRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveProductOrServiceDeploymentProjectSalesandMarketing")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/servicing/{bq-reference-id}/update")
                .id("updateProductOrServiceDeploymentProjectServicing")
                .description("Update details relating to the servicing tasks of the deployment")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Servicing Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Servicing Request Payload")
                .endParam()
                .to("direct:updateProductOrServiceDeploymentProjectServicing")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/servicing/{bq-reference-id}/exchange")
                .id("exchangeProductOrServiceDeploymentProjectServicingUpdate")
                .description("Accept, reject etc. a servicing related task of the deployment")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Servicing Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Servicing request payload")
                .endParam()
                .to("direct:exchangeProductOrServiceDeploymentProjectServicingUpdate")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/servicing/{bq-reference-id}/requisition")
                .id("requestProductOrServiceDeploymentProjectServicingUpdate")
                .description("Request manual intervention in a servicing related deployment task")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Servicing Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Servicing request payload")
                .endParam()
                .to("direct:requestProductOrServiceDeploymentProjectServicingUpdate")
                .get("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/servicing/{bq-reference-id}/")
                .id("retrieveProductOrServiceDeploymentProjectServicing")
                .description("Retrieve details about a servicing related deployment task or deliverable .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Servicing Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQServicingRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveProductOrServiceDeploymentProjectServicing")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/production/{bq-reference-id}/update")
                .id("updateProductOrServiceDeploymentProjectProduction")
                .description("Update details relating to the production tasks of the deployment")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Production Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Production Request Payload")
                .endParam()
                .to("direct:updateProductOrServiceDeploymentProjectProduction")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/production/{bq-reference-id}/exchange")
                .id("exchangeProductOrServiceDeploymentProjectProductionUpdate")
                .description("Accept, reject etc. a production related task of the deployment")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Production Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Production request payload")
                .endParam()
                .to("direct:exchangeProductOrServiceDeploymentProjectProductionUpdate")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/production/{bq-reference-id}/requisition")
                .id("requestProductOrServiceDeploymentProjectProductionUpdate")
                .description("Request manual intervention in a production related deployment task")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Production Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("Production request payload")
                .endParam()
                .to("direct:requestProductOrServiceDeploymentProjectProductionUpdate")
                .get("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/production/{bq-reference-id}/")
                .id("retrieveProductOrServiceDeploymentProjectProduction")
                .description("Retrieve details about a production related deployment task or deliverable .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Production Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQProductionRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveProductOrServiceDeploymentProjectProduction")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/productionsupport/{bq-reference-id}/update")
                .id("updateProductOrServiceDeploymentProjectProductionSupport")
                .description("Update details relating to the production support tasks of the deployment")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("ProductionSupport Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("ProductionSupport Request Payload")
                .endParam()
                .to("direct:updateProductOrServiceDeploymentProjectProductionSupport")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/productionsupport/{bq-reference-id}/exchange")
                .id("exchangeProductOrServiceDeploymentProjectProductionSupportUpdate")
                .description("Accept, reject etc. a production support related task of the deployment")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("ProductionSupport Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("ProductionSupport request payload")
                .endParam()
                .to("direct:exchangeProductOrServiceDeploymentProjectProductionSupportUpdate")
                .put("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/productionsupport/{bq-reference-id}/requisition")
                .id("requestProductOrServiceDeploymentProjectProductionSupportUpdate")
                .description("Request manual intervention in a production support related deployment task")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("ProductionSupport Instance Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("ProductionSupport request payload")
                .endParam()
                .to("direct:requestProductOrServiceDeploymentProjectProductionSupportUpdate");
        rest()
                .get("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/productionsupport/{bq-reference-id}/")
                .id("retrieveProductOrServiceDeploymentProjectProductionSupport")
                .description("Retrieve details about a production support related deployment task or deliverable .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("bq-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("ProductionSupport Instance Reference")
                .endParam()
                .param()
                .name("queryparams")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Query params from schema '#/definitions/BQProductionSupportRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveProductOrServiceDeploymentProjectProductionSupport")
                .get("/product-deployment/{sd-reference-id}/product-or-service-deployment-project")
                .id("RetrieveProductDeploymentReferenceIds")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("collection-filter")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Filter to refine the result set. ex- ProductDeployment Instance Status='active'")
                .endParam()
                .to("direct:RetrieveProductDeploymentReferenceIds")
                .get("/product-deployment/product-or-service-deployment-project/behavior-qualifiers/")
                .id("RetrieveProductDeploymentBehaviorQualifiers")
                .produces("application/json")
                .to("direct:RetrieveProductDeploymentBehaviorQualifiers")
                .get("/product-deployment/{sd-reference-id}/product-or-service-deployment-project/{cr-reference-id}/{behavior-qualifier}/")
                .id("RetrieveProductDeploymentBehaviorQualifierReferenceIds")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Deployment Servicing Session Reference")
                .endParam()
                .param()
                .name("cr-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Product Or Service Deployment Project Instance Reference")
                .endParam()
                .param()
                .name("behavior-qualifier")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Behavior Qualifier Name. ex- ProductionSupport")
                .endParam()
                .param()
                .name("collection-filter")
                .type(RestParamType.query)
                .dataType("string")
                .required(false)
                .description("Filter to refine the result set. ex- ProductionSupport Instance Status = 'pending'")
                .endParam()
                .to("direct:RetrieveProductDeploymentBehaviorQualifierReferenceIds");

                from("direct:createProductOrServiceDeploymentProject")
                        .bean(TransformerBean.class,"create");


    }
}
