version: 2.1

jobs:
  sonar:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn install sonar:sonar -Pcoverage -Dsonar.projectKey=open-accelerators_mercury

workflows:
  main:
    jobs:
      - sonar:
          context: SonarCloud