/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.mercury.customeroffer.model.CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductinitializationbqreferenceidupdateCustomerOfferProcedureInstanceRecord;
import com.redhat.mercury.customeroffer.model.CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductinitializationbqreferenceidupdateProductInitializationInstanceRecord;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Body24
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class Body24 {
  @SerializedName("customerOfferProcedureInstanceRecord")
  private CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductinitializationbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord = null;

  @SerializedName("customerOfferProcedureInstanceReference")
  private String customerOfferProcedureInstanceReference = null;

  @SerializedName("productInitializationInstanceReference")
  private String productInitializationInstanceReference = null;

  @SerializedName("productInitializationInstanceRecord")
  private CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductinitializationbqreferenceidupdateProductInitializationInstanceRecord productInitializationInstanceRecord = null;

  @SerializedName("productInitializationUpdateActionTaskRecord")
  private Object productInitializationUpdateActionTaskRecord = null;

  @SerializedName("productInitializationUpdateActionRequest")
  private String productInitializationUpdateActionRequest = null;

  public Body24 customerOfferProcedureInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductinitializationbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
    return this;
  }

   /**
   * Get customerOfferProcedureInstanceRecord
   * @return customerOfferProcedureInstanceRecord
  **/
  @Schema(description = "")
  public CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductinitializationbqreferenceidupdateCustomerOfferProcedureInstanceRecord getCustomerOfferProcedureInstanceRecord() {
    return customerOfferProcedureInstanceRecord;
  }

  public void setCustomerOfferProcedureInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductinitializationbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
  }

  public Body24 customerOfferProcedureInstanceReference(String customerOfferProcedureInstanceReference) {
    this.customerOfferProcedureInstanceReference = customerOfferProcedureInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Customer Offer Procedure instance 
   * @return customerOfferProcedureInstanceReference
  **/
  @Schema(example = "COPIR749649", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Customer Offer Procedure instance ")
  public String getCustomerOfferProcedureInstanceReference() {
    return customerOfferProcedureInstanceReference;
  }

  public void setCustomerOfferProcedureInstanceReference(String customerOfferProcedureInstanceReference) {
    this.customerOfferProcedureInstanceReference = customerOfferProcedureInstanceReference;
  }

  public Body24 productInitializationInstanceReference(String productInitializationInstanceReference) {
    this.productInitializationInstanceReference = productInitializationInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Product Initialization instance 
   * @return productInitializationInstanceReference
  **/
  @Schema(example = "PIIR723627", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Product Initialization instance ")
  public String getProductInitializationInstanceReference() {
    return productInitializationInstanceReference;
  }

  public void setProductInitializationInstanceReference(String productInitializationInstanceReference) {
    this.productInitializationInstanceReference = productInitializationInstanceReference;
  }

  public Body24 productInitializationInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductinitializationbqreferenceidupdateProductInitializationInstanceRecord productInitializationInstanceRecord) {
    this.productInitializationInstanceRecord = productInitializationInstanceRecord;
    return this;
  }

   /**
   * Get productInitializationInstanceRecord
   * @return productInitializationInstanceRecord
  **/
  @Schema(description = "")
  public CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductinitializationbqreferenceidupdateProductInitializationInstanceRecord getProductInitializationInstanceRecord() {
    return productInitializationInstanceRecord;
  }

  public void setProductInitializationInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductinitializationbqreferenceidupdateProductInitializationInstanceRecord productInitializationInstanceRecord) {
    this.productInitializationInstanceRecord = productInitializationInstanceRecord;
  }

  public Body24 productInitializationUpdateActionTaskRecord(Object productInitializationUpdateActionTaskRecord) {
    this.productInitializationUpdateActionTaskRecord = productInitializationUpdateActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record 
   * @return productInitializationUpdateActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record ")
  public Object getProductInitializationUpdateActionTaskRecord() {
    return productInitializationUpdateActionTaskRecord;
  }

  public void setProductInitializationUpdateActionTaskRecord(Object productInitializationUpdateActionTaskRecord) {
    this.productInitializationUpdateActionTaskRecord = productInitializationUpdateActionTaskRecord;
  }

  public Body24 productInitializationUpdateActionRequest(String productInitializationUpdateActionRequest) {
    this.productInitializationUpdateActionRequest = productInitializationUpdateActionRequest;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the update action service request 
   * @return productInitializationUpdateActionRequest
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the update action service request ")
  public String getProductInitializationUpdateActionRequest() {
    return productInitializationUpdateActionRequest;
  }

  public void setProductInitializationUpdateActionRequest(String productInitializationUpdateActionRequest) {
    this.productInitializationUpdateActionRequest = productInitializationUpdateActionRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body24 body24 = (Body24) o;
    return Objects.equals(this.customerOfferProcedureInstanceRecord, body24.customerOfferProcedureInstanceRecord) &&
        Objects.equals(this.customerOfferProcedureInstanceReference, body24.customerOfferProcedureInstanceReference) &&
        Objects.equals(this.productInitializationInstanceReference, body24.productInitializationInstanceReference) &&
        Objects.equals(this.productInitializationInstanceRecord, body24.productInitializationInstanceRecord) &&
        Objects.equals(this.productInitializationUpdateActionTaskRecord, body24.productInitializationUpdateActionTaskRecord) &&
        Objects.equals(this.productInitializationUpdateActionRequest, body24.productInitializationUpdateActionRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOfferProcedureInstanceRecord, customerOfferProcedureInstanceReference, productInitializationInstanceReference, productInitializationInstanceRecord, productInitializationUpdateActionTaskRecord, productInitializationUpdateActionRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body24 {\n");
    
    sb.append("    customerOfferProcedureInstanceRecord: ").append(toIndentedString(customerOfferProcedureInstanceRecord)).append("\n");
    sb.append("    customerOfferProcedureInstanceReference: ").append(toIndentedString(customerOfferProcedureInstanceReference)).append("\n");
    sb.append("    productInitializationInstanceReference: ").append(toIndentedString(productInitializationInstanceReference)).append("\n");
    sb.append("    productInitializationInstanceRecord: ").append(toIndentedString(productInitializationInstanceRecord)).append("\n");
    sb.append("    productInitializationUpdateActionTaskRecord: ").append(toIndentedString(productInitializationUpdateActionTaskRecord)).append("\n");
    sb.append("    productInitializationUpdateActionRequest: ").append(toIndentedString(productInitializationUpdateActionRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
