/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.mercury.customeroffer.model.CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidexchangeCustomerOfferProcedureExchangeActionRequest;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Body10
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class Body10 {
  @SerializedName("customerOfferProcedureInstanceReference")
  private String customerOfferProcedureInstanceReference = null;

  @SerializedName("productInstanceReference")
  private String productInstanceReference = null;

  @SerializedName("productExchangeActionTaskRecord")
  private Object productExchangeActionTaskRecord = null;

  @SerializedName("productExchangeActionRequest")
  private CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidexchangeCustomerOfferProcedureExchangeActionRequest productExchangeActionRequest = null;

  public Body10 customerOfferProcedureInstanceReference(String customerOfferProcedureInstanceReference) {
    this.customerOfferProcedureInstanceReference = customerOfferProcedureInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Customer Offer Procedure instance 
   * @return customerOfferProcedureInstanceReference
  **/
  @Schema(example = "COPIR785200", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Customer Offer Procedure instance ")
  public String getCustomerOfferProcedureInstanceReference() {
    return customerOfferProcedureInstanceReference;
  }

  public void setCustomerOfferProcedureInstanceReference(String customerOfferProcedureInstanceReference) {
    this.customerOfferProcedureInstanceReference = customerOfferProcedureInstanceReference;
  }

  public Body10 productInstanceReference(String productInstanceReference) {
    this.productInstanceReference = productInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Product instance 
   * @return productInstanceReference
  **/
  @Schema(example = "COPIR785200", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Product instance ")
  public String getProductInstanceReference() {
    return productInstanceReference;
  }

  public void setProductInstanceReference(String productInstanceReference) {
    this.productInstanceReference = productInstanceReference;
  }

  public Body10 productExchangeActionTaskRecord(Object productExchangeActionTaskRecord) {
    this.productExchangeActionTaskRecord = productExchangeActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The exchange service call consolidated processing record 
   * @return productExchangeActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The exchange service call consolidated processing record ")
  public Object getProductExchangeActionTaskRecord() {
    return productExchangeActionTaskRecord;
  }

  public void setProductExchangeActionTaskRecord(Object productExchangeActionTaskRecord) {
    this.productExchangeActionTaskRecord = productExchangeActionTaskRecord;
  }

  public Body10 productExchangeActionRequest(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidexchangeCustomerOfferProcedureExchangeActionRequest productExchangeActionRequest) {
    this.productExchangeActionRequest = productExchangeActionRequest;
    return this;
  }

   /**
   * Get productExchangeActionRequest
   * @return productExchangeActionRequest
  **/
  @Schema(description = "")
  public CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidexchangeCustomerOfferProcedureExchangeActionRequest getProductExchangeActionRequest() {
    return productExchangeActionRequest;
  }

  public void setProductExchangeActionRequest(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidexchangeCustomerOfferProcedureExchangeActionRequest productExchangeActionRequest) {
    this.productExchangeActionRequest = productExchangeActionRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Body10 body10 = (Body10) o;
    return Objects.equals(this.customerOfferProcedureInstanceReference, body10.customerOfferProcedureInstanceReference) &&
        Objects.equals(this.productInstanceReference, body10.productInstanceReference) &&
        Objects.equals(this.productExchangeActionTaskRecord, body10.productExchangeActionTaskRecord) &&
        Objects.equals(this.productExchangeActionRequest, body10.productExchangeActionRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOfferProcedureInstanceReference, productInstanceReference, productExchangeActionTaskRecord, productExchangeActionRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Body10 {\n");
    
    sb.append("    customerOfferProcedureInstanceReference: ").append(toIndentedString(customerOfferProcedureInstanceReference)).append("\n");
    sb.append("    productInstanceReference: ").append(toIndentedString(productInstanceReference)).append("\n");
    sb.append("    productExchangeActionTaskRecord: ").append(toIndentedString(productExchangeActionTaskRecord)).append("\n");
    sb.append("    productExchangeActionRequest: ").append(toIndentedString(productExchangeActionRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
