/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.mercury.customeroffer.model.CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidagreementbqreferenceidupdateAgreementInstanceRecord;
import com.redhat.mercury.customeroffer.model.CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidagreementbqreferenceidupdateCustomerOfferProcedureInstanceRecord;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BQAgreementUpdateOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class BQAgreementUpdateOutputModel {
  @SerializedName("customerOfferProcedureInstanceRecord")
  private CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidagreementbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord = null;

  @SerializedName("agreementInstanceRecord")
  private CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidagreementbqreferenceidupdateAgreementInstanceRecord agreementInstanceRecord = null;

  @SerializedName("agreementUpdateActionTaskReference")
  private String agreementUpdateActionTaskReference = null;

  @SerializedName("agreementUpdateActionTaskRecord")
  private Object agreementUpdateActionTaskRecord = null;

  @SerializedName("updateResponseRecord")
  private Object updateResponseRecord = null;

  public BQAgreementUpdateOutputModel customerOfferProcedureInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidagreementbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
    return this;
  }

   /**
   * Get customerOfferProcedureInstanceRecord
   * @return customerOfferProcedureInstanceRecord
  **/
  @Schema(description = "")
  public CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidagreementbqreferenceidupdateCustomerOfferProcedureInstanceRecord getCustomerOfferProcedureInstanceRecord() {
    return customerOfferProcedureInstanceRecord;
  }

  public void setCustomerOfferProcedureInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidagreementbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
  }

  public BQAgreementUpdateOutputModel agreementInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidagreementbqreferenceidupdateAgreementInstanceRecord agreementInstanceRecord) {
    this.agreementInstanceRecord = agreementInstanceRecord;
    return this;
  }

   /**
   * Get agreementInstanceRecord
   * @return agreementInstanceRecord
  **/
  @Schema(description = "")
  public CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidagreementbqreferenceidupdateAgreementInstanceRecord getAgreementInstanceRecord() {
    return agreementInstanceRecord;
  }

  public void setAgreementInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidagreementbqreferenceidupdateAgreementInstanceRecord agreementInstanceRecord) {
    this.agreementInstanceRecord = agreementInstanceRecord;
  }

  public BQAgreementUpdateOutputModel agreementUpdateActionTaskReference(String agreementUpdateActionTaskReference) {
    this.agreementUpdateActionTaskReference = agreementUpdateActionTaskReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to an update service call 
   * @return agreementUpdateActionTaskReference
  **/
  @Schema(example = "AUATR724260", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to an update service call ")
  public String getAgreementUpdateActionTaskReference() {
    return agreementUpdateActionTaskReference;
  }

  public void setAgreementUpdateActionTaskReference(String agreementUpdateActionTaskReference) {
    this.agreementUpdateActionTaskReference = agreementUpdateActionTaskReference;
  }

  public BQAgreementUpdateOutputModel agreementUpdateActionTaskRecord(Object agreementUpdateActionTaskRecord) {
    this.agreementUpdateActionTaskRecord = agreementUpdateActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record 
   * @return agreementUpdateActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record ")
  public Object getAgreementUpdateActionTaskRecord() {
    return agreementUpdateActionTaskRecord;
  }

  public void setAgreementUpdateActionTaskRecord(Object agreementUpdateActionTaskRecord) {
    this.agreementUpdateActionTaskRecord = agreementUpdateActionTaskRecord;
  }

  public BQAgreementUpdateOutputModel updateResponseRecord(Object updateResponseRecord) {
    this.updateResponseRecord = updateResponseRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: Details of the Update action service response 
   * @return updateResponseRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: Details of the Update action service response ")
  public Object getUpdateResponseRecord() {
    return updateResponseRecord;
  }

  public void setUpdateResponseRecord(Object updateResponseRecord) {
    this.updateResponseRecord = updateResponseRecord;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BQAgreementUpdateOutputModel bqAgreementUpdateOutputModel = (BQAgreementUpdateOutputModel) o;
    return Objects.equals(this.customerOfferProcedureInstanceRecord, bqAgreementUpdateOutputModel.customerOfferProcedureInstanceRecord) &&
        Objects.equals(this.agreementInstanceRecord, bqAgreementUpdateOutputModel.agreementInstanceRecord) &&
        Objects.equals(this.agreementUpdateActionTaskReference, bqAgreementUpdateOutputModel.agreementUpdateActionTaskReference) &&
        Objects.equals(this.agreementUpdateActionTaskRecord, bqAgreementUpdateOutputModel.agreementUpdateActionTaskRecord) &&
        Objects.equals(this.updateResponseRecord, bqAgreementUpdateOutputModel.updateResponseRecord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOfferProcedureInstanceRecord, agreementInstanceRecord, agreementUpdateActionTaskReference, agreementUpdateActionTaskRecord, updateResponseRecord);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BQAgreementUpdateOutputModel {\n");
    
    sb.append("    customerOfferProcedureInstanceRecord: ").append(toIndentedString(customerOfferProcedureInstanceRecord)).append("\n");
    sb.append("    agreementInstanceRecord: ").append(toIndentedString(agreementInstanceRecord)).append("\n");
    sb.append("    agreementUpdateActionTaskReference: ").append(toIndentedString(agreementUpdateActionTaskReference)).append("\n");
    sb.append("    agreementUpdateActionTaskRecord: ").append(toIndentedString(agreementUpdateActionTaskRecord)).append("\n");
    sb.append("    updateResponseRecord: ").append(toIndentedString(updateResponseRecord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
