/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.mercury.customeroffer.model.CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidcreditbqreferenceidupdateCreditInstanceRecord;
import com.redhat.mercury.customeroffer.model.CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidcreditbqreferenceidupdateCustomerOfferProcedureInstanceRecord;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BQCreditUpdateInputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class BQCreditUpdateInputModel {
  @SerializedName("customerOfferProcedureInstanceRecord")
  private CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidcreditbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord = null;

  @SerializedName("customerOfferProcedureInstanceReference")
  private String customerOfferProcedureInstanceReference = null;

  @SerializedName("creditInstanceReference")
  private String creditInstanceReference = null;

  @SerializedName("creditInstanceRecord")
  private CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidcreditbqreferenceidupdateCreditInstanceRecord creditInstanceRecord = null;

  @SerializedName("creditUpdateActionTaskRecord")
  private Object creditUpdateActionTaskRecord = null;

  @SerializedName("creditUpdateActionRequest")
  private String creditUpdateActionRequest = null;

  public BQCreditUpdateInputModel customerOfferProcedureInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidcreditbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
    return this;
  }

   /**
   * Get customerOfferProcedureInstanceRecord
   * @return customerOfferProcedureInstanceRecord
  **/
  @Schema(description = "")
  public CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidcreditbqreferenceidupdateCustomerOfferProcedureInstanceRecord getCustomerOfferProcedureInstanceRecord() {
    return customerOfferProcedureInstanceRecord;
  }

  public void setCustomerOfferProcedureInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidcreditbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
  }

  public BQCreditUpdateInputModel customerOfferProcedureInstanceReference(String customerOfferProcedureInstanceReference) {
    this.customerOfferProcedureInstanceReference = customerOfferProcedureInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Customer Offer Procedure instance 
   * @return customerOfferProcedureInstanceReference
  **/
  @Schema(example = "COPIR762563", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Customer Offer Procedure instance ")
  public String getCustomerOfferProcedureInstanceReference() {
    return customerOfferProcedureInstanceReference;
  }

  public void setCustomerOfferProcedureInstanceReference(String customerOfferProcedureInstanceReference) {
    this.customerOfferProcedureInstanceReference = customerOfferProcedureInstanceReference;
  }

  public BQCreditUpdateInputModel creditInstanceReference(String creditInstanceReference) {
    this.creditInstanceReference = creditInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Credit instance 
   * @return creditInstanceReference
  **/
  @Schema(example = "CIR792446", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Credit instance ")
  public String getCreditInstanceReference() {
    return creditInstanceReference;
  }

  public void setCreditInstanceReference(String creditInstanceReference) {
    this.creditInstanceReference = creditInstanceReference;
  }

  public BQCreditUpdateInputModel creditInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidcreditbqreferenceidupdateCreditInstanceRecord creditInstanceRecord) {
    this.creditInstanceRecord = creditInstanceRecord;
    return this;
  }

   /**
   * Get creditInstanceRecord
   * @return creditInstanceRecord
  **/
  @Schema(description = "")
  public CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidcreditbqreferenceidupdateCreditInstanceRecord getCreditInstanceRecord() {
    return creditInstanceRecord;
  }

  public void setCreditInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidcreditbqreferenceidupdateCreditInstanceRecord creditInstanceRecord) {
    this.creditInstanceRecord = creditInstanceRecord;
  }

  public BQCreditUpdateInputModel creditUpdateActionTaskRecord(Object creditUpdateActionTaskRecord) {
    this.creditUpdateActionTaskRecord = creditUpdateActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record 
   * @return creditUpdateActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record ")
  public Object getCreditUpdateActionTaskRecord() {
    return creditUpdateActionTaskRecord;
  }

  public void setCreditUpdateActionTaskRecord(Object creditUpdateActionTaskRecord) {
    this.creditUpdateActionTaskRecord = creditUpdateActionTaskRecord;
  }

  public BQCreditUpdateInputModel creditUpdateActionRequest(String creditUpdateActionRequest) {
    this.creditUpdateActionRequest = creditUpdateActionRequest;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the update action service request 
   * @return creditUpdateActionRequest
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the update action service request ")
  public String getCreditUpdateActionRequest() {
    return creditUpdateActionRequest;
  }

  public void setCreditUpdateActionRequest(String creditUpdateActionRequest) {
    this.creditUpdateActionRequest = creditUpdateActionRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BQCreditUpdateInputModel bqCreditUpdateInputModel = (BQCreditUpdateInputModel) o;
    return Objects.equals(this.customerOfferProcedureInstanceRecord, bqCreditUpdateInputModel.customerOfferProcedureInstanceRecord) &&
        Objects.equals(this.customerOfferProcedureInstanceReference, bqCreditUpdateInputModel.customerOfferProcedureInstanceReference) &&
        Objects.equals(this.creditInstanceReference, bqCreditUpdateInputModel.creditInstanceReference) &&
        Objects.equals(this.creditInstanceRecord, bqCreditUpdateInputModel.creditInstanceRecord) &&
        Objects.equals(this.creditUpdateActionTaskRecord, bqCreditUpdateInputModel.creditUpdateActionTaskRecord) &&
        Objects.equals(this.creditUpdateActionRequest, bqCreditUpdateInputModel.creditUpdateActionRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOfferProcedureInstanceRecord, customerOfferProcedureInstanceReference, creditInstanceReference, creditInstanceRecord, creditUpdateActionTaskRecord, creditUpdateActionRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BQCreditUpdateInputModel {\n");
    
    sb.append("    customerOfferProcedureInstanceRecord: ").append(toIndentedString(customerOfferProcedureInstanceRecord)).append("\n");
    sb.append("    customerOfferProcedureInstanceReference: ").append(toIndentedString(customerOfferProcedureInstanceReference)).append("\n");
    sb.append("    creditInstanceReference: ").append(toIndentedString(creditInstanceReference)).append("\n");
    sb.append("    creditInstanceRecord: ").append(toIndentedString(creditInstanceRecord)).append("\n");
    sb.append("    creditUpdateActionTaskRecord: ").append(toIndentedString(creditUpdateActionTaskRecord)).append("\n");
    sb.append("    creditUpdateActionRequest: ").append(toIndentedString(creditUpdateActionRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
