/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.mercury.customeroffer.model.CustomeroffersdreferenceidcustomerofferprocedurecrreferenceiddisclosuresbqreferenceidupdateCustomerOfferProcedureInstanceRecord;
import com.redhat.mercury.customeroffer.model.CustomeroffersdreferenceidcustomerofferprocedurecrreferenceiddisclosuresbqreferenceidupdateDisclosuresInstanceRecord;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BQDisclosuresUpdateInputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class BQDisclosuresUpdateInputModel {
  @SerializedName("customerOfferProcedureInstanceRecord")
  private CustomeroffersdreferenceidcustomerofferprocedurecrreferenceiddisclosuresbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord = null;

  @SerializedName("customerOfferProcedureInstanceReference")
  private String customerOfferProcedureInstanceReference = null;

  @SerializedName("disclosuresInstanceReference")
  private String disclosuresInstanceReference = null;

  @SerializedName("disclosuresInstanceRecord")
  private CustomeroffersdreferenceidcustomerofferprocedurecrreferenceiddisclosuresbqreferenceidupdateDisclosuresInstanceRecord disclosuresInstanceRecord = null;

  @SerializedName("disclosuresUpdateActionTaskRecord")
  private Object disclosuresUpdateActionTaskRecord = null;

  @SerializedName("disclosuresUpdateActionRequest")
  private String disclosuresUpdateActionRequest = null;

  public BQDisclosuresUpdateInputModel customerOfferProcedureInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceiddisclosuresbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
    return this;
  }

   /**
   * Get customerOfferProcedureInstanceRecord
   * @return customerOfferProcedureInstanceRecord
  **/
  @Schema(description = "")
  public CustomeroffersdreferenceidcustomerofferprocedurecrreferenceiddisclosuresbqreferenceidupdateCustomerOfferProcedureInstanceRecord getCustomerOfferProcedureInstanceRecord() {
    return customerOfferProcedureInstanceRecord;
  }

  public void setCustomerOfferProcedureInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceiddisclosuresbqreferenceidupdateCustomerOfferProcedureInstanceRecord customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
  }

  public BQDisclosuresUpdateInputModel customerOfferProcedureInstanceReference(String customerOfferProcedureInstanceReference) {
    this.customerOfferProcedureInstanceReference = customerOfferProcedureInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Customer Offer Procedure instance 
   * @return customerOfferProcedureInstanceReference
  **/
  @Schema(example = "COPIR703181", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the parent Customer Offer Procedure instance ")
  public String getCustomerOfferProcedureInstanceReference() {
    return customerOfferProcedureInstanceReference;
  }

  public void setCustomerOfferProcedureInstanceReference(String customerOfferProcedureInstanceReference) {
    this.customerOfferProcedureInstanceReference = customerOfferProcedureInstanceReference;
  }

  public BQDisclosuresUpdateInputModel disclosuresInstanceReference(String disclosuresInstanceReference) {
    this.disclosuresInstanceReference = disclosuresInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Disclosures instance 
   * @return disclosuresInstanceReference
  **/
  @Schema(example = "DIR774723", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Disclosures instance ")
  public String getDisclosuresInstanceReference() {
    return disclosuresInstanceReference;
  }

  public void setDisclosuresInstanceReference(String disclosuresInstanceReference) {
    this.disclosuresInstanceReference = disclosuresInstanceReference;
  }

  public BQDisclosuresUpdateInputModel disclosuresInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceiddisclosuresbqreferenceidupdateDisclosuresInstanceRecord disclosuresInstanceRecord) {
    this.disclosuresInstanceRecord = disclosuresInstanceRecord;
    return this;
  }

   /**
   * Get disclosuresInstanceRecord
   * @return disclosuresInstanceRecord
  **/
  @Schema(description = "")
  public CustomeroffersdreferenceidcustomerofferprocedurecrreferenceiddisclosuresbqreferenceidupdateDisclosuresInstanceRecord getDisclosuresInstanceRecord() {
    return disclosuresInstanceRecord;
  }

  public void setDisclosuresInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceiddisclosuresbqreferenceidupdateDisclosuresInstanceRecord disclosuresInstanceRecord) {
    this.disclosuresInstanceRecord = disclosuresInstanceRecord;
  }

  public BQDisclosuresUpdateInputModel disclosuresUpdateActionTaskRecord(Object disclosuresUpdateActionTaskRecord) {
    this.disclosuresUpdateActionTaskRecord = disclosuresUpdateActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record 
   * @return disclosuresUpdateActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record ")
  public Object getDisclosuresUpdateActionTaskRecord() {
    return disclosuresUpdateActionTaskRecord;
  }

  public void setDisclosuresUpdateActionTaskRecord(Object disclosuresUpdateActionTaskRecord) {
    this.disclosuresUpdateActionTaskRecord = disclosuresUpdateActionTaskRecord;
  }

  public BQDisclosuresUpdateInputModel disclosuresUpdateActionRequest(String disclosuresUpdateActionRequest) {
    this.disclosuresUpdateActionRequest = disclosuresUpdateActionRequest;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the update action service request 
   * @return disclosuresUpdateActionRequest
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the update action service request ")
  public String getDisclosuresUpdateActionRequest() {
    return disclosuresUpdateActionRequest;
  }

  public void setDisclosuresUpdateActionRequest(String disclosuresUpdateActionRequest) {
    this.disclosuresUpdateActionRequest = disclosuresUpdateActionRequest;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BQDisclosuresUpdateInputModel bqDisclosuresUpdateInputModel = (BQDisclosuresUpdateInputModel) o;
    return Objects.equals(this.customerOfferProcedureInstanceRecord, bqDisclosuresUpdateInputModel.customerOfferProcedureInstanceRecord) &&
        Objects.equals(this.customerOfferProcedureInstanceReference, bqDisclosuresUpdateInputModel.customerOfferProcedureInstanceReference) &&
        Objects.equals(this.disclosuresInstanceReference, bqDisclosuresUpdateInputModel.disclosuresInstanceReference) &&
        Objects.equals(this.disclosuresInstanceRecord, bqDisclosuresUpdateInputModel.disclosuresInstanceRecord) &&
        Objects.equals(this.disclosuresUpdateActionTaskRecord, bqDisclosuresUpdateInputModel.disclosuresUpdateActionTaskRecord) &&
        Objects.equals(this.disclosuresUpdateActionRequest, bqDisclosuresUpdateInputModel.disclosuresUpdateActionRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOfferProcedureInstanceRecord, customerOfferProcedureInstanceReference, disclosuresInstanceReference, disclosuresInstanceRecord, disclosuresUpdateActionTaskRecord, disclosuresUpdateActionRequest);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BQDisclosuresUpdateInputModel {\n");
    
    sb.append("    customerOfferProcedureInstanceRecord: ").append(toIndentedString(customerOfferProcedureInstanceRecord)).append("\n");
    sb.append("    customerOfferProcedureInstanceReference: ").append(toIndentedString(customerOfferProcedureInstanceReference)).append("\n");
    sb.append("    disclosuresInstanceReference: ").append(toIndentedString(disclosuresInstanceReference)).append("\n");
    sb.append("    disclosuresInstanceRecord: ").append(toIndentedString(disclosuresInstanceRecord)).append("\n");
    sb.append("    disclosuresUpdateActionTaskRecord: ").append(toIndentedString(disclosuresUpdateActionTaskRecord)).append("\n");
    sb.append("    disclosuresUpdateActionRequest: ").append(toIndentedString(disclosuresUpdateActionRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
