/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.mercury.customeroffer.model.BQProductInitializationRetrieveOutputModelCustomerOfferProcedureInstanceRecord1;
import com.redhat.mercury.customeroffer.model.BQProductInitializationRetrieveOutputModelProductInitializationInstanceAnalysis1;
import com.redhat.mercury.customeroffer.model.BQProductInitializationRetrieveOutputModelProductInitializationInstanceRecord1;
import com.redhat.mercury.customeroffer.model.BQProductInitializationRetrieveOutputModelProductInitializationInstanceReport1;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BQProductInitializationRetrieveOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class BQProductInitializationRetrieveOutputModel {
  @SerializedName("customerOfferProcedureInstanceRecord")
  private BQProductInitializationRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord = null;

  @SerializedName("productInitializationInstanceRecord")
  private BQProductInitializationRetrieveOutputModelProductInitializationInstanceRecord1 productInitializationInstanceRecord = null;

  @SerializedName("productInitializationRetrieveActionTaskReference")
  private String productInitializationRetrieveActionTaskReference = null;

  @SerializedName("productInitializationRetrieveActionTaskRecord")
  private Object productInitializationRetrieveActionTaskRecord = null;

  @SerializedName("productInitializationRetrieveActionResponse")
  private String productInitializationRetrieveActionResponse = null;

  @SerializedName("productInitializationInstanceReport")
  private BQProductInitializationRetrieveOutputModelProductInitializationInstanceReport1 productInitializationInstanceReport = null;

  @SerializedName("productInitializationInstanceAnalysis")
  private BQProductInitializationRetrieveOutputModelProductInitializationInstanceAnalysis1 productInitializationInstanceAnalysis = null;

  public BQProductInitializationRetrieveOutputModel customerOfferProcedureInstanceRecord(BQProductInitializationRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
    return this;
  }

   /**
   * Get customerOfferProcedureInstanceRecord
   * @return customerOfferProcedureInstanceRecord
  **/
  @Schema(description = "")
  public BQProductInitializationRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 getCustomerOfferProcedureInstanceRecord() {
    return customerOfferProcedureInstanceRecord;
  }

  public void setCustomerOfferProcedureInstanceRecord(BQProductInitializationRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
  }

  public BQProductInitializationRetrieveOutputModel productInitializationInstanceRecord(BQProductInitializationRetrieveOutputModelProductInitializationInstanceRecord1 productInitializationInstanceRecord) {
    this.productInitializationInstanceRecord = productInitializationInstanceRecord;
    return this;
  }

   /**
   * Get productInitializationInstanceRecord
   * @return productInitializationInstanceRecord
  **/
  @Schema(description = "")
  public BQProductInitializationRetrieveOutputModelProductInitializationInstanceRecord1 getProductInitializationInstanceRecord() {
    return productInitializationInstanceRecord;
  }

  public void setProductInitializationInstanceRecord(BQProductInitializationRetrieveOutputModelProductInitializationInstanceRecord1 productInitializationInstanceRecord) {
    this.productInitializationInstanceRecord = productInitializationInstanceRecord;
  }

  public BQProductInitializationRetrieveOutputModel productInitializationRetrieveActionTaskReference(String productInitializationRetrieveActionTaskReference) {
    this.productInitializationRetrieveActionTaskReference = productInitializationRetrieveActionTaskReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Product Initialization instance retrieve service call 
   * @return productInitializationRetrieveActionTaskReference
  **/
  @Schema(example = "PIRATR716347", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Product Initialization instance retrieve service call ")
  public String getProductInitializationRetrieveActionTaskReference() {
    return productInitializationRetrieveActionTaskReference;
  }

  public void setProductInitializationRetrieveActionTaskReference(String productInitializationRetrieveActionTaskReference) {
    this.productInitializationRetrieveActionTaskReference = productInitializationRetrieveActionTaskReference;
  }

  public BQProductInitializationRetrieveOutputModel productInitializationRetrieveActionTaskRecord(Object productInitializationRetrieveActionTaskRecord) {
    this.productInitializationRetrieveActionTaskRecord = productInitializationRetrieveActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record 
   * @return productInitializationRetrieveActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record ")
  public Object getProductInitializationRetrieveActionTaskRecord() {
    return productInitializationRetrieveActionTaskRecord;
  }

  public void setProductInitializationRetrieveActionTaskRecord(Object productInitializationRetrieveActionTaskRecord) {
    this.productInitializationRetrieveActionTaskRecord = productInitializationRetrieveActionTaskRecord;
  }

  public BQProductInitializationRetrieveOutputModel productInitializationRetrieveActionResponse(String productInitializationRetrieveActionResponse) {
    this.productInitializationRetrieveActionResponse = productInitializationRetrieveActionResponse;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) 
   * @return productInitializationRetrieveActionResponse
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) ")
  public String getProductInitializationRetrieveActionResponse() {
    return productInitializationRetrieveActionResponse;
  }

  public void setProductInitializationRetrieveActionResponse(String productInitializationRetrieveActionResponse) {
    this.productInitializationRetrieveActionResponse = productInitializationRetrieveActionResponse;
  }

  public BQProductInitializationRetrieveOutputModel productInitializationInstanceReport(BQProductInitializationRetrieveOutputModelProductInitializationInstanceReport1 productInitializationInstanceReport) {
    this.productInitializationInstanceReport = productInitializationInstanceReport;
    return this;
  }

   /**
   * Get productInitializationInstanceReport
   * @return productInitializationInstanceReport
  **/
  @Schema(description = "")
  public BQProductInitializationRetrieveOutputModelProductInitializationInstanceReport1 getProductInitializationInstanceReport() {
    return productInitializationInstanceReport;
  }

  public void setProductInitializationInstanceReport(BQProductInitializationRetrieveOutputModelProductInitializationInstanceReport1 productInitializationInstanceReport) {
    this.productInitializationInstanceReport = productInitializationInstanceReport;
  }

  public BQProductInitializationRetrieveOutputModel productInitializationInstanceAnalysis(BQProductInitializationRetrieveOutputModelProductInitializationInstanceAnalysis1 productInitializationInstanceAnalysis) {
    this.productInitializationInstanceAnalysis = productInitializationInstanceAnalysis;
    return this;
  }

   /**
   * Get productInitializationInstanceAnalysis
   * @return productInitializationInstanceAnalysis
  **/
  @Schema(description = "")
  public BQProductInitializationRetrieveOutputModelProductInitializationInstanceAnalysis1 getProductInitializationInstanceAnalysis() {
    return productInitializationInstanceAnalysis;
  }

  public void setProductInitializationInstanceAnalysis(BQProductInitializationRetrieveOutputModelProductInitializationInstanceAnalysis1 productInitializationInstanceAnalysis) {
    this.productInitializationInstanceAnalysis = productInitializationInstanceAnalysis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BQProductInitializationRetrieveOutputModel bqProductInitializationRetrieveOutputModel = (BQProductInitializationRetrieveOutputModel) o;
    return Objects.equals(this.customerOfferProcedureInstanceRecord, bqProductInitializationRetrieveOutputModel.customerOfferProcedureInstanceRecord) &&
        Objects.equals(this.productInitializationInstanceRecord, bqProductInitializationRetrieveOutputModel.productInitializationInstanceRecord) &&
        Objects.equals(this.productInitializationRetrieveActionTaskReference, bqProductInitializationRetrieveOutputModel.productInitializationRetrieveActionTaskReference) &&
        Objects.equals(this.productInitializationRetrieveActionTaskRecord, bqProductInitializationRetrieveOutputModel.productInitializationRetrieveActionTaskRecord) &&
        Objects.equals(this.productInitializationRetrieveActionResponse, bqProductInitializationRetrieveOutputModel.productInitializationRetrieveActionResponse) &&
        Objects.equals(this.productInitializationInstanceReport, bqProductInitializationRetrieveOutputModel.productInitializationInstanceReport) &&
        Objects.equals(this.productInitializationInstanceAnalysis, bqProductInitializationRetrieveOutputModel.productInitializationInstanceAnalysis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOfferProcedureInstanceRecord, productInitializationInstanceRecord, productInitializationRetrieveActionTaskReference, productInitializationRetrieveActionTaskRecord, productInitializationRetrieveActionResponse, productInitializationInstanceReport, productInitializationInstanceAnalysis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BQProductInitializationRetrieveOutputModel {\n");
    
    sb.append("    customerOfferProcedureInstanceRecord: ").append(toIndentedString(customerOfferProcedureInstanceRecord)).append("\n");
    sb.append("    productInitializationInstanceRecord: ").append(toIndentedString(productInitializationInstanceRecord)).append("\n");
    sb.append("    productInitializationRetrieveActionTaskReference: ").append(toIndentedString(productInitializationRetrieveActionTaskReference)).append("\n");
    sb.append("    productInitializationRetrieveActionTaskRecord: ").append(toIndentedString(productInitializationRetrieveActionTaskRecord)).append("\n");
    sb.append("    productInitializationRetrieveActionResponse: ").append(toIndentedString(productInitializationRetrieveActionResponse)).append("\n");
    sb.append("    productInitializationInstanceReport: ").append(toIndentedString(productInitializationInstanceReport)).append("\n");
    sb.append("    productInitializationInstanceAnalysis: ").append(toIndentedString(productInitializationInstanceAnalysis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
