/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.mercury.customeroffer.model.BQProductInitializationRetrieveInputModelProductInitializationInstanceAnalysis1;
import com.redhat.mercury.customeroffer.model.BQProductInitializationRetrieveInputModelProductInitializationInstanceReport1;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BQProductInitializationRetrieveInputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class BQProductInitializationRetrieveInputModel {
  @SerializedName("productInitializationRetrieveActionTaskRecord")
  private Object productInitializationRetrieveActionTaskRecord = null;

  @SerializedName("productInitializationRetrieveActionRequest")
  private String productInitializationRetrieveActionRequest = null;

  @SerializedName("productInitializationInstanceReport")
  private BQProductInitializationRetrieveInputModelProductInitializationInstanceReport1 productInitializationInstanceReport = null;

  @SerializedName("productInitializationInstanceAnalysis")
  private BQProductInitializationRetrieveInputModelProductInitializationInstanceAnalysis1 productInitializationInstanceAnalysis = null;

  public BQProductInitializationRetrieveInputModel productInitializationRetrieveActionTaskRecord(Object productInitializationRetrieveActionTaskRecord) {
    this.productInitializationRetrieveActionTaskRecord = productInitializationRetrieveActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record 
   * @return productInitializationRetrieveActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record ")
  public Object getProductInitializationRetrieveActionTaskRecord() {
    return productInitializationRetrieveActionTaskRecord;
  }

  public void setProductInitializationRetrieveActionTaskRecord(Object productInitializationRetrieveActionTaskRecord) {
    this.productInitializationRetrieveActionTaskRecord = productInitializationRetrieveActionTaskRecord;
  }

  public BQProductInitializationRetrieveInputModel productInitializationRetrieveActionRequest(String productInitializationRetrieveActionRequest) {
    this.productInitializationRetrieveActionRequest = productInitializationRetrieveActionRequest;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service request (lists requested reports) 
   * @return productInitializationRetrieveActionRequest
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service request (lists requested reports) ")
  public String getProductInitializationRetrieveActionRequest() {
    return productInitializationRetrieveActionRequest;
  }

  public void setProductInitializationRetrieveActionRequest(String productInitializationRetrieveActionRequest) {
    this.productInitializationRetrieveActionRequest = productInitializationRetrieveActionRequest;
  }

  public BQProductInitializationRetrieveInputModel productInitializationInstanceReport(BQProductInitializationRetrieveInputModelProductInitializationInstanceReport1 productInitializationInstanceReport) {
    this.productInitializationInstanceReport = productInitializationInstanceReport;
    return this;
  }

   /**
   * Get productInitializationInstanceReport
   * @return productInitializationInstanceReport
  **/
  @Schema(description = "")
  public BQProductInitializationRetrieveInputModelProductInitializationInstanceReport1 getProductInitializationInstanceReport() {
    return productInitializationInstanceReport;
  }

  public void setProductInitializationInstanceReport(BQProductInitializationRetrieveInputModelProductInitializationInstanceReport1 productInitializationInstanceReport) {
    this.productInitializationInstanceReport = productInitializationInstanceReport;
  }

  public BQProductInitializationRetrieveInputModel productInitializationInstanceAnalysis(BQProductInitializationRetrieveInputModelProductInitializationInstanceAnalysis1 productInitializationInstanceAnalysis) {
    this.productInitializationInstanceAnalysis = productInitializationInstanceAnalysis;
    return this;
  }

   /**
   * Get productInitializationInstanceAnalysis
   * @return productInitializationInstanceAnalysis
  **/
  @Schema(description = "")
  public BQProductInitializationRetrieveInputModelProductInitializationInstanceAnalysis1 getProductInitializationInstanceAnalysis() {
    return productInitializationInstanceAnalysis;
  }

  public void setProductInitializationInstanceAnalysis(BQProductInitializationRetrieveInputModelProductInitializationInstanceAnalysis1 productInitializationInstanceAnalysis) {
    this.productInitializationInstanceAnalysis = productInitializationInstanceAnalysis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BQProductInitializationRetrieveInputModel bqProductInitializationRetrieveInputModel = (BQProductInitializationRetrieveInputModel) o;
    return Objects.equals(this.productInitializationRetrieveActionTaskRecord, bqProductInitializationRetrieveInputModel.productInitializationRetrieveActionTaskRecord) &&
        Objects.equals(this.productInitializationRetrieveActionRequest, bqProductInitializationRetrieveInputModel.productInitializationRetrieveActionRequest) &&
        Objects.equals(this.productInitializationInstanceReport, bqProductInitializationRetrieveInputModel.productInitializationInstanceReport) &&
        Objects.equals(this.productInitializationInstanceAnalysis, bqProductInitializationRetrieveInputModel.productInitializationInstanceAnalysis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productInitializationRetrieveActionTaskRecord, productInitializationRetrieveActionRequest, productInitializationInstanceReport, productInitializationInstanceAnalysis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BQProductInitializationRetrieveInputModel {\n");
    
    sb.append("    productInitializationRetrieveActionTaskRecord: ").append(toIndentedString(productInitializationRetrieveActionTaskRecord)).append("\n");
    sb.append("    productInitializationRetrieveActionRequest: ").append(toIndentedString(productInitializationRetrieveActionRequest)).append("\n");
    sb.append("    productInitializationInstanceReport: ").append(toIndentedString(productInitializationInstanceReport)).append("\n");
    sb.append("    productInitializationInstanceAnalysis: ").append(toIndentedString(productInitializationInstanceAnalysis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
