/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.mercury.customeroffer.model.CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceAnalysis1;
import com.redhat.mercury.customeroffer.model.CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceRecord1;
import com.redhat.mercury.customeroffer.model.CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceReportRecord1;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CRCustomerOfferProcedureRetrieveOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class CRCustomerOfferProcedureRetrieveOutputModel {
  @SerializedName("customerOfferProcedureInstanceRecord")
  private CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord = null;

  @SerializedName("customerOfferProcedureRetrieveActionTaskReference")
  private String customerOfferProcedureRetrieveActionTaskReference = null;

  @SerializedName("customerOfferProcedureRetrieveActionTaskRecord")
  private Object customerOfferProcedureRetrieveActionTaskRecord = null;

  @SerializedName("customerOfferProcedureRetrieveActionResponse")
  private String customerOfferProcedureRetrieveActionResponse = null;

  @SerializedName("customerOfferProcedureInstanceReportRecord")
  private CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceReportRecord1 customerOfferProcedureInstanceReportRecord = null;

  @SerializedName("customerOfferProcedureInstanceAnalysis")
  private CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceAnalysis1 customerOfferProcedureInstanceAnalysis = null;

  public CRCustomerOfferProcedureRetrieveOutputModel customerOfferProcedureInstanceRecord(CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
    return this;
  }

   /**
   * Get customerOfferProcedureInstanceRecord
   * @return customerOfferProcedureInstanceRecord
  **/
  @Schema(description = "")
  public CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 getCustomerOfferProcedureInstanceRecord() {
    return customerOfferProcedureInstanceRecord;
  }

  public void setCustomerOfferProcedureInstanceRecord(CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
  }

  public CRCustomerOfferProcedureRetrieveOutputModel customerOfferProcedureRetrieveActionTaskReference(String customerOfferProcedureRetrieveActionTaskReference) {
    this.customerOfferProcedureRetrieveActionTaskReference = customerOfferProcedureRetrieveActionTaskReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Customer Offer Procedure instance retrieve service call 
   * @return customerOfferProcedureRetrieveActionTaskReference
  **/
  @Schema(example = "COPRATR785437", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Customer Offer Procedure instance retrieve service call ")
  public String getCustomerOfferProcedureRetrieveActionTaskReference() {
    return customerOfferProcedureRetrieveActionTaskReference;
  }

  public void setCustomerOfferProcedureRetrieveActionTaskReference(String customerOfferProcedureRetrieveActionTaskReference) {
    this.customerOfferProcedureRetrieveActionTaskReference = customerOfferProcedureRetrieveActionTaskReference;
  }

  public CRCustomerOfferProcedureRetrieveOutputModel customerOfferProcedureRetrieveActionTaskRecord(Object customerOfferProcedureRetrieveActionTaskRecord) {
    this.customerOfferProcedureRetrieveActionTaskRecord = customerOfferProcedureRetrieveActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record 
   * @return customerOfferProcedureRetrieveActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record ")
  public Object getCustomerOfferProcedureRetrieveActionTaskRecord() {
    return customerOfferProcedureRetrieveActionTaskRecord;
  }

  public void setCustomerOfferProcedureRetrieveActionTaskRecord(Object customerOfferProcedureRetrieveActionTaskRecord) {
    this.customerOfferProcedureRetrieveActionTaskRecord = customerOfferProcedureRetrieveActionTaskRecord;
  }

  public CRCustomerOfferProcedureRetrieveOutputModel customerOfferProcedureRetrieveActionResponse(String customerOfferProcedureRetrieveActionResponse) {
    this.customerOfferProcedureRetrieveActionResponse = customerOfferProcedureRetrieveActionResponse;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) 
   * @return customerOfferProcedureRetrieveActionResponse
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) ")
  public String getCustomerOfferProcedureRetrieveActionResponse() {
    return customerOfferProcedureRetrieveActionResponse;
  }

  public void setCustomerOfferProcedureRetrieveActionResponse(String customerOfferProcedureRetrieveActionResponse) {
    this.customerOfferProcedureRetrieveActionResponse = customerOfferProcedureRetrieveActionResponse;
  }

  public CRCustomerOfferProcedureRetrieveOutputModel customerOfferProcedureInstanceReportRecord(CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceReportRecord1 customerOfferProcedureInstanceReportRecord) {
    this.customerOfferProcedureInstanceReportRecord = customerOfferProcedureInstanceReportRecord;
    return this;
  }

   /**
   * Get customerOfferProcedureInstanceReportRecord
   * @return customerOfferProcedureInstanceReportRecord
  **/
  @Schema(description = "")
  public CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceReportRecord1 getCustomerOfferProcedureInstanceReportRecord() {
    return customerOfferProcedureInstanceReportRecord;
  }

  public void setCustomerOfferProcedureInstanceReportRecord(CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceReportRecord1 customerOfferProcedureInstanceReportRecord) {
    this.customerOfferProcedureInstanceReportRecord = customerOfferProcedureInstanceReportRecord;
  }

  public CRCustomerOfferProcedureRetrieveOutputModel customerOfferProcedureInstanceAnalysis(CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceAnalysis1 customerOfferProcedureInstanceAnalysis) {
    this.customerOfferProcedureInstanceAnalysis = customerOfferProcedureInstanceAnalysis;
    return this;
  }

   /**
   * Get customerOfferProcedureInstanceAnalysis
   * @return customerOfferProcedureInstanceAnalysis
  **/
  @Schema(description = "")
  public CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceAnalysis1 getCustomerOfferProcedureInstanceAnalysis() {
    return customerOfferProcedureInstanceAnalysis;
  }

  public void setCustomerOfferProcedureInstanceAnalysis(CRCustomerOfferProcedureRetrieveOutputModelCustomerOfferProcedureInstanceAnalysis1 customerOfferProcedureInstanceAnalysis) {
    this.customerOfferProcedureInstanceAnalysis = customerOfferProcedureInstanceAnalysis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CRCustomerOfferProcedureRetrieveOutputModel crCustomerOfferProcedureRetrieveOutputModel = (CRCustomerOfferProcedureRetrieveOutputModel) o;
    return Objects.equals(this.customerOfferProcedureInstanceRecord, crCustomerOfferProcedureRetrieveOutputModel.customerOfferProcedureInstanceRecord) &&
        Objects.equals(this.customerOfferProcedureRetrieveActionTaskReference, crCustomerOfferProcedureRetrieveOutputModel.customerOfferProcedureRetrieveActionTaskReference) &&
        Objects.equals(this.customerOfferProcedureRetrieveActionTaskRecord, crCustomerOfferProcedureRetrieveOutputModel.customerOfferProcedureRetrieveActionTaskRecord) &&
        Objects.equals(this.customerOfferProcedureRetrieveActionResponse, crCustomerOfferProcedureRetrieveOutputModel.customerOfferProcedureRetrieveActionResponse) &&
        Objects.equals(this.customerOfferProcedureInstanceReportRecord, crCustomerOfferProcedureRetrieveOutputModel.customerOfferProcedureInstanceReportRecord) &&
        Objects.equals(this.customerOfferProcedureInstanceAnalysis, crCustomerOfferProcedureRetrieveOutputModel.customerOfferProcedureInstanceAnalysis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOfferProcedureInstanceRecord, customerOfferProcedureRetrieveActionTaskReference, customerOfferProcedureRetrieveActionTaskRecord, customerOfferProcedureRetrieveActionResponse, customerOfferProcedureInstanceReportRecord, customerOfferProcedureInstanceAnalysis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CRCustomerOfferProcedureRetrieveOutputModel {\n");
    
    sb.append("    customerOfferProcedureInstanceRecord: ").append(toIndentedString(customerOfferProcedureInstanceRecord)).append("\n");
    sb.append("    customerOfferProcedureRetrieveActionTaskReference: ").append(toIndentedString(customerOfferProcedureRetrieveActionTaskReference)).append("\n");
    sb.append("    customerOfferProcedureRetrieveActionTaskRecord: ").append(toIndentedString(customerOfferProcedureRetrieveActionTaskRecord)).append("\n");
    sb.append("    customerOfferProcedureRetrieveActionResponse: ").append(toIndentedString(customerOfferProcedureRetrieveActionResponse)).append("\n");
    sb.append("    customerOfferProcedureInstanceReportRecord: ").append(toIndentedString(customerOfferProcedureInstanceReportRecord)).append("\n");
    sb.append("    customerOfferProcedureInstanceAnalysis: ").append(toIndentedString(customerOfferProcedureInstanceAnalysis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
