/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CRCustomerOfferProcedureInitiateOutputModelDisclosuresInstanceRecord
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class CRCustomerOfferProcedureInitiateOutputModelDisclosuresInstanceRecord {
  @SerializedName("disclosureType")
  private String disclosureType = null;

  @SerializedName("disclosureTextDescription")
  private String disclosureTextDescription = null;

  public CRCustomerOfferProcedureInitiateOutputModelDisclosuresInstanceRecord disclosureType(String disclosureType) {
    this.disclosureType = disclosureType;
    return this;
  }

   /**
   * &#x60;status: Registered&#x60;  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_9ju10HltEeG7BsjMvd1mEw_-739610260/elements/_9j4m0HltEeG7BsjMvd1mEw_-611051048  bian-reference: CustomerOffer.OfferedAgreement(as Agreement).Disclosure.DisclosureType  general-info: The type of disclosure (e.g. verbal, requiring signature) 
   * @return disclosureType
  **/
  @Schema(description = "`status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_9ju10HltEeG7BsjMvd1mEw_-739610260/elements/_9j4m0HltEeG7BsjMvd1mEw_-611051048  bian-reference: CustomerOffer.OfferedAgreement(as Agreement).Disclosure.DisclosureType  general-info: The type of disclosure (e.g. verbal, requiring signature) ")
  public String getDisclosureType() {
    return disclosureType;
  }

  public void setDisclosureType(String disclosureType) {
    this.disclosureType = disclosureType;
  }

  public CRCustomerOfferProcedureInitiateOutputModelDisclosuresInstanceRecord disclosureTextDescription(String disclosureTextDescription) {
    this.disclosureTextDescription = disclosureTextDescription;
    return this;
  }

   /**
   * &#x60;status: Registered&#x60;  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_9ju10HltEeG7BsjMvd1mEw_-739610260/elements/_9j4m0XltEeG7BsjMvd1mEw_369279782  bian-reference: CustomerOffer.OfferedAgreement(as Agreement).Disclosure.DisclosureDescription  general-info: The presented disclosure for customer review in any suitable format 
   * @return disclosureTextDescription
  **/
  @Schema(description = "`status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_9ju10HltEeG7BsjMvd1mEw_-739610260/elements/_9j4m0XltEeG7BsjMvd1mEw_369279782  bian-reference: CustomerOffer.OfferedAgreement(as Agreement).Disclosure.DisclosureDescription  general-info: The presented disclosure for customer review in any suitable format ")
  public String getDisclosureTextDescription() {
    return disclosureTextDescription;
  }

  public void setDisclosureTextDescription(String disclosureTextDescription) {
    this.disclosureTextDescription = disclosureTextDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CRCustomerOfferProcedureInitiateOutputModelDisclosuresInstanceRecord crCustomerOfferProcedureInitiateOutputModelDisclosuresInstanceRecord = (CRCustomerOfferProcedureInitiateOutputModelDisclosuresInstanceRecord) o;
    return Objects.equals(this.disclosureType, crCustomerOfferProcedureInitiateOutputModelDisclosuresInstanceRecord.disclosureType) &&
        Objects.equals(this.disclosureTextDescription, crCustomerOfferProcedureInitiateOutputModelDisclosuresInstanceRecord.disclosureTextDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disclosureType, disclosureTextDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CRCustomerOfferProcedureInitiateOutputModelDisclosuresInstanceRecord {\n");
    
    sb.append("    disclosureType: ").append(toIndentedString(disclosureType)).append("\n");
    sb.append("    disclosureTextDescription: ").append(toIndentedString(disclosureTextDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
