/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CustomeroffersdreferenceidcustomerofferprocedureinitiationCorrespondenceandDocumentsInstanceRecord
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class CustomeroffersdreferenceidcustomerofferprocedureinitiationCorrespondenceandDocumentsInstanceRecord {
  @SerializedName("customerOfferRequiredDocuments")
  private String customerOfferRequiredDocuments = null;

  public CustomeroffersdreferenceidcustomerofferprocedureinitiationCorrespondenceandDocumentsInstanceRecord customerOfferRequiredDocuments(String customerOfferRequiredDocuments) {
    this.customerOfferRequiredDocuments = customerOfferRequiredDocuments;
    return this;
  }

   /**
   * &#x60;status: Registered&#x60;  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNET28TGEeChad0JzLk7QA_1924783636  bian-reference: Document  general-info: Description of the required documents and time limits on receipt where appropriate 
   * @return customerOfferRequiredDocuments
  **/
  @Schema(description = "`status: Registered`  iso-link: https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/bc/_FNET28TGEeChad0JzLk7QA_1924783636  bian-reference: Document  general-info: Description of the required documents and time limits on receipt where appropriate ")
  public String getCustomerOfferRequiredDocuments() {
    return customerOfferRequiredDocuments;
  }

  public void setCustomerOfferRequiredDocuments(String customerOfferRequiredDocuments) {
    this.customerOfferRequiredDocuments = customerOfferRequiredDocuments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomeroffersdreferenceidcustomerofferprocedureinitiationCorrespondenceandDocumentsInstanceRecord customeroffersdreferenceidcustomerofferprocedureinitiationCorrespondenceandDocumentsInstanceRecord = (CustomeroffersdreferenceidcustomerofferprocedureinitiationCorrespondenceandDocumentsInstanceRecord) o;
    return Objects.equals(this.customerOfferRequiredDocuments, customeroffersdreferenceidcustomerofferprocedureinitiationCorrespondenceandDocumentsInstanceRecord.customerOfferRequiredDocuments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOfferRequiredDocuments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomeroffersdreferenceidcustomerofferprocedureinitiationCorrespondenceandDocumentsInstanceRecord {\n");
    
    sb.append("    customerOfferRequiredDocuments: ").append(toIndentedString(customerOfferRequiredDocuments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
