/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.mercury.customeroffer.model.BQProductRetrieveOutputModelCustomerOfferProcedureInstanceRecord1;
import com.redhat.mercury.customeroffer.model.BQProductRetrieveOutputModelProductInstanceAnalysis1;
import com.redhat.mercury.customeroffer.model.BQProductRetrieveOutputModelProductInstanceReport1;
import com.redhat.mercury.customeroffer.model.CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductbqreferenceidupdateProductInstanceRecord;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20011
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class InlineResponse20011 {
  @SerializedName("customerOfferProcedureInstanceRecord")
  private BQProductRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord = null;

  @SerializedName("productInstanceRecord")
  private CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductbqreferenceidupdateProductInstanceRecord productInstanceRecord = null;

  @SerializedName("productRetrieveActionTaskReference")
  private String productRetrieveActionTaskReference = null;

  @SerializedName("productRetrieveActionTaskRecord")
  private Object productRetrieveActionTaskRecord = null;

  @SerializedName("productRetrieveActionResponse")
  private String productRetrieveActionResponse = null;

  @SerializedName("productInstanceReport")
  private BQProductRetrieveOutputModelProductInstanceReport1 productInstanceReport = null;

  @SerializedName("productInstanceAnalysis")
  private BQProductRetrieveOutputModelProductInstanceAnalysis1 productInstanceAnalysis = null;

  public InlineResponse20011 customerOfferProcedureInstanceRecord(BQProductRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
    return this;
  }

   /**
   * Get customerOfferProcedureInstanceRecord
   * @return customerOfferProcedureInstanceRecord
  **/
  @Schema(description = "")
  public BQProductRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 getCustomerOfferProcedureInstanceRecord() {
    return customerOfferProcedureInstanceRecord;
  }

  public void setCustomerOfferProcedureInstanceRecord(BQProductRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
  }

  public InlineResponse20011 productInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductbqreferenceidupdateProductInstanceRecord productInstanceRecord) {
    this.productInstanceRecord = productInstanceRecord;
    return this;
  }

   /**
   * Get productInstanceRecord
   * @return productInstanceRecord
  **/
  @Schema(description = "")
  public CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductbqreferenceidupdateProductInstanceRecord getProductInstanceRecord() {
    return productInstanceRecord;
  }

  public void setProductInstanceRecord(CustomeroffersdreferenceidcustomerofferprocedurecrreferenceidproductbqreferenceidupdateProductInstanceRecord productInstanceRecord) {
    this.productInstanceRecord = productInstanceRecord;
  }

  public InlineResponse20011 productRetrieveActionTaskReference(String productRetrieveActionTaskReference) {
    this.productRetrieveActionTaskReference = productRetrieveActionTaskReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Product instance retrieve service call 
   * @return productRetrieveActionTaskReference
  **/
  @Schema(example = "COPRATR747428", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Product instance retrieve service call ")
  public String getProductRetrieveActionTaskReference() {
    return productRetrieveActionTaskReference;
  }

  public void setProductRetrieveActionTaskReference(String productRetrieveActionTaskReference) {
    this.productRetrieveActionTaskReference = productRetrieveActionTaskReference;
  }

  public InlineResponse20011 productRetrieveActionTaskRecord(Object productRetrieveActionTaskRecord) {
    this.productRetrieveActionTaskRecord = productRetrieveActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record 
   * @return productRetrieveActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record ")
  public Object getProductRetrieveActionTaskRecord() {
    return productRetrieveActionTaskRecord;
  }

  public void setProductRetrieveActionTaskRecord(Object productRetrieveActionTaskRecord) {
    this.productRetrieveActionTaskRecord = productRetrieveActionTaskRecord;
  }

  public InlineResponse20011 productRetrieveActionResponse(String productRetrieveActionResponse) {
    this.productRetrieveActionResponse = productRetrieveActionResponse;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) 
   * @return productRetrieveActionResponse
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) ")
  public String getProductRetrieveActionResponse() {
    return productRetrieveActionResponse;
  }

  public void setProductRetrieveActionResponse(String productRetrieveActionResponse) {
    this.productRetrieveActionResponse = productRetrieveActionResponse;
  }

  public InlineResponse20011 productInstanceReport(BQProductRetrieveOutputModelProductInstanceReport1 productInstanceReport) {
    this.productInstanceReport = productInstanceReport;
    return this;
  }

   /**
   * Get productInstanceReport
   * @return productInstanceReport
  **/
  @Schema(description = "")
  public BQProductRetrieveOutputModelProductInstanceReport1 getProductInstanceReport() {
    return productInstanceReport;
  }

  public void setProductInstanceReport(BQProductRetrieveOutputModelProductInstanceReport1 productInstanceReport) {
    this.productInstanceReport = productInstanceReport;
  }

  public InlineResponse20011 productInstanceAnalysis(BQProductRetrieveOutputModelProductInstanceAnalysis1 productInstanceAnalysis) {
    this.productInstanceAnalysis = productInstanceAnalysis;
    return this;
  }

   /**
   * Get productInstanceAnalysis
   * @return productInstanceAnalysis
  **/
  @Schema(description = "")
  public BQProductRetrieveOutputModelProductInstanceAnalysis1 getProductInstanceAnalysis() {
    return productInstanceAnalysis;
  }

  public void setProductInstanceAnalysis(BQProductRetrieveOutputModelProductInstanceAnalysis1 productInstanceAnalysis) {
    this.productInstanceAnalysis = productInstanceAnalysis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20011 inlineResponse20011 = (InlineResponse20011) o;
    return Objects.equals(this.customerOfferProcedureInstanceRecord, inlineResponse20011.customerOfferProcedureInstanceRecord) &&
        Objects.equals(this.productInstanceRecord, inlineResponse20011.productInstanceRecord) &&
        Objects.equals(this.productRetrieveActionTaskReference, inlineResponse20011.productRetrieveActionTaskReference) &&
        Objects.equals(this.productRetrieveActionTaskRecord, inlineResponse20011.productRetrieveActionTaskRecord) &&
        Objects.equals(this.productRetrieveActionResponse, inlineResponse20011.productRetrieveActionResponse) &&
        Objects.equals(this.productInstanceReport, inlineResponse20011.productInstanceReport) &&
        Objects.equals(this.productInstanceAnalysis, inlineResponse20011.productInstanceAnalysis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOfferProcedureInstanceRecord, productInstanceRecord, productRetrieveActionTaskReference, productRetrieveActionTaskRecord, productRetrieveActionResponse, productInstanceReport, productInstanceAnalysis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20011 {\n");
    
    sb.append("    customerOfferProcedureInstanceRecord: ").append(toIndentedString(customerOfferProcedureInstanceRecord)).append("\n");
    sb.append("    productInstanceRecord: ").append(toIndentedString(productInstanceRecord)).append("\n");
    sb.append("    productRetrieveActionTaskReference: ").append(toIndentedString(productRetrieveActionTaskReference)).append("\n");
    sb.append("    productRetrieveActionTaskRecord: ").append(toIndentedString(productRetrieveActionTaskRecord)).append("\n");
    sb.append("    productRetrieveActionResponse: ").append(toIndentedString(productRetrieveActionResponse)).append("\n");
    sb.append("    productInstanceReport: ").append(toIndentedString(productInstanceReport)).append("\n");
    sb.append("    productInstanceAnalysis: ").append(toIndentedString(productInstanceAnalysis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
