/*
 * Customer Offer
 * This service domain orchestrates the processing of a product offer for a new/established  customer.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customeroffer.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.redhat.mercury.customeroffer.model.BQUnderwritingRetrieveOutputModelCustomerOfferProcedureInstanceRecord1;
import com.redhat.mercury.customeroffer.model.BQUnderwritingRetrieveOutputModelUnderwritingInstanceAnalysis1;
import com.redhat.mercury.customeroffer.model.BQUnderwritingRetrieveOutputModelUnderwritingInstanceRecord1;
import com.redhat.mercury.customeroffer.model.BQUnderwritingRetrieveOutputModelUnderwritingInstanceReport1;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20018
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-11-19T11:10:08.827631+01:00[Europe/Madrid]")
public class InlineResponse20018 {
  @SerializedName("customerOfferProcedureInstanceRecord")
  private BQUnderwritingRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord = null;

  @SerializedName("underwritingInstanceRecord")
  private BQUnderwritingRetrieveOutputModelUnderwritingInstanceRecord1 underwritingInstanceRecord = null;

  @SerializedName("underwritingRetrieveActionTaskReference")
  private String underwritingRetrieveActionTaskReference = null;

  @SerializedName("underwritingRetrieveActionTaskRecord")
  private Object underwritingRetrieveActionTaskRecord = null;

  @SerializedName("underwritingRetrieveActionResponse")
  private String underwritingRetrieveActionResponse = null;

  @SerializedName("underwritingInstanceReport")
  private BQUnderwritingRetrieveOutputModelUnderwritingInstanceReport1 underwritingInstanceReport = null;

  @SerializedName("underwritingInstanceAnalysis")
  private BQUnderwritingRetrieveOutputModelUnderwritingInstanceAnalysis1 underwritingInstanceAnalysis = null;

  public InlineResponse20018 customerOfferProcedureInstanceRecord(BQUnderwritingRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
    return this;
  }

   /**
   * Get customerOfferProcedureInstanceRecord
   * @return customerOfferProcedureInstanceRecord
  **/
  @Schema(description = "")
  public BQUnderwritingRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 getCustomerOfferProcedureInstanceRecord() {
    return customerOfferProcedureInstanceRecord;
  }

  public void setCustomerOfferProcedureInstanceRecord(BQUnderwritingRetrieveOutputModelCustomerOfferProcedureInstanceRecord1 customerOfferProcedureInstanceRecord) {
    this.customerOfferProcedureInstanceRecord = customerOfferProcedureInstanceRecord;
  }

  public InlineResponse20018 underwritingInstanceRecord(BQUnderwritingRetrieveOutputModelUnderwritingInstanceRecord1 underwritingInstanceRecord) {
    this.underwritingInstanceRecord = underwritingInstanceRecord;
    return this;
  }

   /**
   * Get underwritingInstanceRecord
   * @return underwritingInstanceRecord
  **/
  @Schema(description = "")
  public BQUnderwritingRetrieveOutputModelUnderwritingInstanceRecord1 getUnderwritingInstanceRecord() {
    return underwritingInstanceRecord;
  }

  public void setUnderwritingInstanceRecord(BQUnderwritingRetrieveOutputModelUnderwritingInstanceRecord1 underwritingInstanceRecord) {
    this.underwritingInstanceRecord = underwritingInstanceRecord;
  }

  public InlineResponse20018 underwritingRetrieveActionTaskReference(String underwritingRetrieveActionTaskReference) {
    this.underwritingRetrieveActionTaskReference = underwritingRetrieveActionTaskReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Underwriting instance retrieve service call 
   * @return underwritingRetrieveActionTaskReference
  **/
  @Schema(example = "URATR735691", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Underwriting instance retrieve service call ")
  public String getUnderwritingRetrieveActionTaskReference() {
    return underwritingRetrieveActionTaskReference;
  }

  public void setUnderwritingRetrieveActionTaskReference(String underwritingRetrieveActionTaskReference) {
    this.underwritingRetrieveActionTaskReference = underwritingRetrieveActionTaskReference;
  }

  public InlineResponse20018 underwritingRetrieveActionTaskRecord(Object underwritingRetrieveActionTaskRecord) {
    this.underwritingRetrieveActionTaskRecord = underwritingRetrieveActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record 
   * @return underwritingRetrieveActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record ")
  public Object getUnderwritingRetrieveActionTaskRecord() {
    return underwritingRetrieveActionTaskRecord;
  }

  public void setUnderwritingRetrieveActionTaskRecord(Object underwritingRetrieveActionTaskRecord) {
    this.underwritingRetrieveActionTaskRecord = underwritingRetrieveActionTaskRecord;
  }

  public InlineResponse20018 underwritingRetrieveActionResponse(String underwritingRetrieveActionResponse) {
    this.underwritingRetrieveActionResponse = underwritingRetrieveActionResponse;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) 
   * @return underwritingRetrieveActionResponse
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) ")
  public String getUnderwritingRetrieveActionResponse() {
    return underwritingRetrieveActionResponse;
  }

  public void setUnderwritingRetrieveActionResponse(String underwritingRetrieveActionResponse) {
    this.underwritingRetrieveActionResponse = underwritingRetrieveActionResponse;
  }

  public InlineResponse20018 underwritingInstanceReport(BQUnderwritingRetrieveOutputModelUnderwritingInstanceReport1 underwritingInstanceReport) {
    this.underwritingInstanceReport = underwritingInstanceReport;
    return this;
  }

   /**
   * Get underwritingInstanceReport
   * @return underwritingInstanceReport
  **/
  @Schema(description = "")
  public BQUnderwritingRetrieveOutputModelUnderwritingInstanceReport1 getUnderwritingInstanceReport() {
    return underwritingInstanceReport;
  }

  public void setUnderwritingInstanceReport(BQUnderwritingRetrieveOutputModelUnderwritingInstanceReport1 underwritingInstanceReport) {
    this.underwritingInstanceReport = underwritingInstanceReport;
  }

  public InlineResponse20018 underwritingInstanceAnalysis(BQUnderwritingRetrieveOutputModelUnderwritingInstanceAnalysis1 underwritingInstanceAnalysis) {
    this.underwritingInstanceAnalysis = underwritingInstanceAnalysis;
    return this;
  }

   /**
   * Get underwritingInstanceAnalysis
   * @return underwritingInstanceAnalysis
  **/
  @Schema(description = "")
  public BQUnderwritingRetrieveOutputModelUnderwritingInstanceAnalysis1 getUnderwritingInstanceAnalysis() {
    return underwritingInstanceAnalysis;
  }

  public void setUnderwritingInstanceAnalysis(BQUnderwritingRetrieveOutputModelUnderwritingInstanceAnalysis1 underwritingInstanceAnalysis) {
    this.underwritingInstanceAnalysis = underwritingInstanceAnalysis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20018 inlineResponse20018 = (InlineResponse20018) o;
    return Objects.equals(this.customerOfferProcedureInstanceRecord, inlineResponse20018.customerOfferProcedureInstanceRecord) &&
        Objects.equals(this.underwritingInstanceRecord, inlineResponse20018.underwritingInstanceRecord) &&
        Objects.equals(this.underwritingRetrieveActionTaskReference, inlineResponse20018.underwritingRetrieveActionTaskReference) &&
        Objects.equals(this.underwritingRetrieveActionTaskRecord, inlineResponse20018.underwritingRetrieveActionTaskRecord) &&
        Objects.equals(this.underwritingRetrieveActionResponse, inlineResponse20018.underwritingRetrieveActionResponse) &&
        Objects.equals(this.underwritingInstanceReport, inlineResponse20018.underwritingInstanceReport) &&
        Objects.equals(this.underwritingInstanceAnalysis, inlineResponse20018.underwritingInstanceAnalysis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerOfferProcedureInstanceRecord, underwritingInstanceRecord, underwritingRetrieveActionTaskReference, underwritingRetrieveActionTaskRecord, underwritingRetrieveActionResponse, underwritingInstanceReport, underwritingInstanceAnalysis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20018 {\n");
    
    sb.append("    customerOfferProcedureInstanceRecord: ").append(toIndentedString(customerOfferProcedureInstanceRecord)).append("\n");
    sb.append("    underwritingInstanceRecord: ").append(toIndentedString(underwritingInstanceRecord)).append("\n");
    sb.append("    underwritingRetrieveActionTaskReference: ").append(toIndentedString(underwritingRetrieveActionTaskReference)).append("\n");
    sb.append("    underwritingRetrieveActionTaskRecord: ").append(toIndentedString(underwritingRetrieveActionTaskRecord)).append("\n");
    sb.append("    underwritingRetrieveActionResponse: ").append(toIndentedString(underwritingRetrieveActionResponse)).append("\n");
    sb.append("    underwritingInstanceReport: ").append(toIndentedString(underwritingInstanceReport)).append("\n");
    sb.append("    underwritingInstanceAnalysis: ").append(toIndentedString(underwritingInstanceAnalysis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
