apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: bm
spec:
  features:
    async: 
      enabled: true
      defaultBinding: KAFKA
      defaultFrequency: 10
      kafka:
        install: false
        url: coreless-kafka-kafka-bootstrap:9092
  keycloak:
    install: false
    realm: mercury
    # This will have to be changed depending on the generated keycloak route
    url: keycloak-mercury-common.bian-coreless-df320be24f0424156040b8c0440947c1-0000.us-south.containers.appdomain.cloud
    privateUrl: http://keycloak-discovery.mercury-common.svc.cluster.local:8080
    serviceAccount: microcks-serviceaccount
    serviceAccountCredentials: super-secret
  microcks:
    replicas: 1
  mongodb:
    install: true
    persistent: true
    volumeSize: 2Gi
  name: bm
  postman:
    replicas: 1
  version: 1.3.0