apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-camel-k
  namespace: mercury-common
  labels:
    operators.coreos.com/rhsso-operator.mercury-common: ""
spec:
  channel: 1.4.x
  installPlanApproval: Automatic
  name: red-hat-camel-k
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: red-hat-camel-k-operator.v1.4.0