apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: mercury-admin
spec:
  user:
    username: admin
    firstName: Admin
    lastName: Istrator
    enabled: True
    emailVerified: False
    credentials:
      - type: password
        value: RedHat1!
    realmRoles:
      - "offline_access"
      - "uma_authorization"
    clientRoles:
      account:
        - "manage-account"
        - "view-profile"
      realm-management:
        - "manage-users"
        - "view-users"
        - "query-users"
        - "create-client"
  realmSelector:
    matchLabels:
      app: mercury
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: mercury-bernie
spec:
  user:
    username: bernie
    firstName: Bernard
    lastName: Bernoulli
    enabled: True
    emailVerified: False
    credentials:
      - type: password
        value: purple
  realmSelector:
    matchLabels:
      app: mercury