apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mercury-operator-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: mercury-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: mercury-operator
    namespace: mercury