package com.redhat.customeroffer;

import javax.annotation.Generated;

import org.apache.camel.Exchange;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.component.servlet.CamelHttpTransportServlet;
import org.apache.camel.model.rest.RestBindingMode;
import org.apache.camel.model.rest.RestParamType;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

/**
 * Generated from Swagger specification by Camel REST DSL generator.
 */
@Generated("org.apache.camel.generator.swagger.PathGenerator")
@Component
public final class CamelRoutes extends RouteBuilder {
    /**
     * Defines Apache Camel routes using REST DSL fluent API.
     */


    @Bean
    public ServletRegistrationBean servletRegistrationBean() {
        ServletRegistrationBean registration = new ServletRegistrationBean(new CamelHttpTransportServlet(), "/service/*");
        registration.setName("CamelServlet");
        return registration;
    }
    @Value("${oc.project.path}")
    String projectPath;

    @Value("${eligibility.url}")
    String elibilityURL;

    @Value("${directory.url}")
    String directoryURL;

    @Value("${deployment.url}")
    String deploymentURL;

    public void configure() {

        restConfiguration()
                .component("servlet")

                .bindingMode(RestBindingMode.auto)
                .producerComponent("http4")
                .apiContextPath("/swagger") //swagger endpoint path
                .apiContextRouteId("swagger") //id of route providing the swagger endpoint
                .host(projectPath)
                .contextPath("/service")
                //Swagger properties

                .apiProperty("api.title", "Example REST api")
                .apiProperty("api.version", "1.0")
                .apiProperty("api.path","/service")
                .producerComponent("http4")
        ;
        rest()
            .post("/customer-offer/activation")
                .id("activateSDCustomerOffer")
                .description("Activate  a  SDCustomerOffer servicing session")
                .produces("application/json")
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("SDCustomerOffer Request Payload")
                .endParam()
                .to("direct:activateSDCustomerOffer")
            .put("/customer-offer/{sd-reference-id}/configuration")
                .id("configureSDCustomerOffer")
                .description("Update an active SDCustomerOffer session configuration")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("SDCustomerOffer Servicing Session Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("SDCustomerOffer Configure Request Payload")
                .endParam()
                .to("direct:configureSDCustomerOffer")
            .put("/customer-offer/{sd-reference-id}/feedback")
                .id("feedbackSDCustomerOffer")
                .description("Capturing feedback against the SDCustomerOffer service that can target different levels of detail: SD/CR/BQ")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("SDCustomerOffer Servicing Session Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("SDCustomerOffer Feedback Request Payload")
                .endParam()
                .to("direct:feedbackSDCustomerOffer")
            .get("/customer-offer/{sd-reference-id}")
                .id("retrieveSDCustomerOffer")
                .description("Analytical views maintained by the SDCustomerOffer service center for management reporting and analysis purposes")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("SDCustomerOffer Servicing Session Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/SDCustomerOfferRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveSDCustomerOffer")

            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/update")
                .id("updateCustomerOfferProcedure")
                .description("Update details of an offer procedure")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Offer Procedure Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedure")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/control")
                .id("controlCustomerOfferProcedureUpdate")
                .description("Control the processing of an offer (e.g. terminate)")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Offer Procedure Request Payload")
                .endParam()
                .to("direct:controlCustomerOfferProcedureUpdate")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/exchange")
                .id("exchangeCustomerOfferProcedureUpdate")
                .description("Accept, reject, verify, etc an offer procedure")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Offer Procedure Request Payload")
                .endParam()
                .to("direct:exchangeCustomerOfferProcedureUpdate")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/execution")
                .id("executeCustomerOfferProcedureUpdate")
                .description("Execute an automated task against an offer (e.g. submit data)")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Offer Procedure Request Payload")
                .endParam()
                .to("direct:executeCustomerOfferProcedureUpdate")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/requisition")
                .id("requestCustomerOfferProcedureUpdate")
                .description("Request manual intervention in an offer (e.g. request specialist support)")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Customer Offer Procedure Request Payload")
                .endParam()
                .to("direct:requestCustomerOfferProcedureUpdate")
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}")
                .id("retrieveCustomerOffer")
                .description("Retrieve details about a customer offer")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/CRCustomerOfferProcedureRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOffer");
        rest()
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/product/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureProduct")
                .description("Update product options and pricing terms")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Product Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureProduct")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/product/{bq-reference-id}/exchange")
                .id("exchangeCustomerOfferProcedureProductUpdate")
                .description("Accept, reject etc product options and pricing terms")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Product request payload")
                .endParam()
                .to("direct:exchangeCustomerOfferProcedureProductUpdate");
        rest()
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/product/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureProduct")
                .description("Retrieve details about product options and pricing terms .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Product Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQProductRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureProduct");
        rest()
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/disclosures/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureDisclosures")
                .description("Update disclosure submission")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Disclosures Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Disclosures Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureDisclosures")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/disclosures/{bq-reference-id}/exchange")
                .id("exchangeCustomerOfferProcedureDisclosuresUpdate")
                .description("Accept, reject etc. disclosures")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Disclosures Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Disclosures request payload")
                .endParam()
                .to("direct:exchangeCustomerOfferProcedureDisclosuresUpdate")
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/disclosures/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureDisclosures")
                .description("Retrieve details about disclosure submissions .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Disclosures Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQDisclosuresRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureDisclosures")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/credit/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureCredit")
                .description("Update credit submission details")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Credit Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Credit Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureCredit");
                rest()
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/credit/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureCredit")
                .description("Retrieve details about the credit submission .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Credit Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQCreditRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureCredit")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/underwriting/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureUnderwriting")
                .description("Update submitted materials for the underwriting decision")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Underwriting Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Underwriting Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureUnderwriting")
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/underwriting/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureUnderwriting")
                .description("Retrieve details about the underwriting decision .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Underwriting Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQUnderwritingRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureUnderwriting");
                rest()
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/compliance/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureCompliance")
                .description("Update details submitted for compliance checks")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Compliance Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Compliance Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureCompliance")
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/compliance/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureCompliance")
                .description("Retrieve details of the regulatory compliance assessment .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Compliance Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQComplianceRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureCompliance")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/audit/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureAudit")
                .description("Update details of submitted materials for audit checks")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Audit Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Audit Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureAudit")
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/audit/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureAudit")
                .description("Retrieve details of the compliance assessment .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Audit Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQAuditRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureAudit")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/collateral/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureCollateral")
                .description("Update details of the collateral allocation")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Collateral Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Collateral Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureCollateral")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/collateral/{bq-reference-id}/exchange")
                .id("exchangeCustomerOfferProcedureCollateralUpdate")
                .description("Accept, reject etc. the collateral allocation")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Collateral Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Collateral request payload")
                .endParam()
                .to("direct:exchangeCustomerOfferProcedureCollateralUpdate");
        rest()
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/collateral/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureCollateral")
                .description("Retrieve details about the collateral allocation .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Collateral Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQCollateralRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureCollateral")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/booking/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureBooking")
                .description("Update details of the offer asset and liability booking")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Booking Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Booking Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureBooking")
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/booking/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureBooking")
                .description("Retrieve details about the booking .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Booking Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQBookingRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureBooking")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/correspondenceanddocuments/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureCorrespondenceandDocuments")
                .description("Update details about the correspondence and documents accessed and created by the offer")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("CorrespondenceandDocuments Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("CorrespondenceandDocuments Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureCorrespondenceandDocuments")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/correspondenceanddocuments/{bq-reference-id}/exchange")
                .id("exchangeCustomerOfferProcedureCorrespondenceandDocumentsUpdate")
                .description("Accept, verify, etc. correspondence and documents")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("CorrespondenceandDocuments Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("CorrespondenceandDocuments request payload")
                .endParam()
                .to("direct:exchangeCustomerOfferProcedureCorrespondenceandDocumentsUpdate")
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/correspondenceanddocuments/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureCorrespondenceandDocuments")
                .description("Retrieve details about correspondence and documents from the customer offer procedure .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("CorrespondenceandDocuments Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQCorrespondenceandDocumentsRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureCorrespondenceandDocuments")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/agreement/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureAgreement")
                .description("Update details of the customer agreement")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Agreement Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Agreement Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureAgreement");
        rest()
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/agreement/{bq-reference-id}/exchange")
                .id("exchangeCustomerOfferProcedureAgreementUpdate")
                .description("Accept, verify, etc. actions against the customer and product agreements")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Agreement Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("Agreement request payload")
                .endParam()
                .to("direct:exchangeCustomerOfferProcedureAgreementUpdate")
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/agreement/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureAgreement")
                .description("Retrieve details about the agreements impacted and created as part of the offer .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Agreement Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQAgreementRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureAgreement")
            .put("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/productinitialization/{bq-reference-id}/update")
                .id("updateCustomerOfferProcedureProductInitialization")
                .description("Update details of the product initiation request")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("ProductInitialization Instance Reference")
                .endParam()
                .param()
                    .name("body")
                    .type(RestParamType.body)
                    .required(true)
                    .description("ProductInitialization Request Payload")
                .endParam()
                .to("direct:updateCustomerOfferProcedureProductInitialization");
        rest()
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/productinitialization/{bq-reference-id}/")
                .id("retrieveCustomerOfferProcedureProductInitialization")
                .description("Retrieve details about the product initiation request .The retrieve operation can have sub qualifiers beyond BQ level, please reffer to the model heriarchy to extend beyond BQ level into APIs retrieving sub-qualifier level information.")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("bq-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("ProductInitialization Instance Reference")
                .endParam()
                .param()
                    .name("queryparams")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Query params from schema '#/definitions/BQProductInitializationRetrieveInputModel'")
                .endParam()
                .to("direct:retrieveCustomerOfferProcedureProductInitialization")
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure")
                .id("RetrieveCustomerOfferReferenceIds")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("collection-filter")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Filter to refine the result set. ex- CustomerOffer Instance Status='active'")
                .endParam()
                .to("direct:RetrieveCustomerOfferReferenceIds")
            .get("/customer-offer/customer-offer-procedure/behavior-qualifiers/")
                .id("RetrieveCustomerOfferBehaviorQualifiers")
                .produces("application/json")
                .to("direct:RetrieveCustomerOfferBehaviorQualifiers")
            .get("/customer-offer/{sd-reference-id}/customer-offer-procedure/{cr-reference-id}/{behavior-qualifier}/")
                .id("RetrieveCustomerOfferBehaviorQualifierReferenceIds")
                .produces("application/json")
                .param()
                    .name("sd-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                    .name("cr-reference-id")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Customer Offer Procedure Instance Reference")
                .endParam()
                .param()
                    .name("behavior-qualifier")
                    .type(RestParamType.path)
                    .dataType("string")
                    .required(true)
                    .description("Behavior Qualifier Name. ex- ProductInitialization")
                .endParam()
                .param()
                    .name("collection-filter")
                    .type(RestParamType.query)
                    .dataType("string")
                    .required(false)
                    .description("Filter to refine the result set. ex- ProductInitialization Instance Status = 'pending'")
                .endParam()
                .to("direct:RetrieveCustomerOfferBehaviorQualifierReferenceIds");


        rest()
        .post("/customer-offer/{sd-reference-id}/customer-offer-procedure/initiation")
                .id("initiateCustomerOfferProcedure")
                .description("Initiate the offer procedure")
                .produces("application/json")
                .param()
                .name("sd-reference-id")
                .type(RestParamType.path)
                .dataType("string")
                .required(true)
                .description("Customer Offer Servicing Session Reference")
                .endParam()
                .param()
                .name("body")
                .type(RestParamType.body)
                .required(true)
                .description("CustomerOfferProcedure Request Payload")
                .endParam()
                .route()
                .id("initiateCustomerOfferProcedure")
                .bean(TransformerBean.class,"extractRequest")
                .id("Extract Request Parameters")
                .removeHeader(Exchange.HTTP_PATH)
                .id("Prepare Headers")
                .setHeader(Exchange.HTTP_METHOD, constant("GET"))
                .id("Prepare GET HTTP operation")

                .toD("http4://"+directoryURL+"/${body}?bridgeEndpoint=true")
                .id("Invoke Retrieve Product Specification")
                .bean(TransformerBean.class,"initiateAppDownload")
                .id("Prepare request object for initiating app download")
                .removeHeader(Exchange.HTTP_PATH)
                .id("Prepare Headers")
                .setHeader(Exchange.HTTP_METHOD, constant("POST"))
                .id("Prepare POST HTTP operation")
                .toD("http4://"+deploymentURL+"/product-deployment/${header.sdRefId}/product-or-service-deployment-project/creation?bridgeEndpoint=true")
                .id("Invoke Initiate App Download")
                .bean(TransformerBean.class,"updateProductEligibility")
                .id("Prepare request Object for update product usage")
                .removeHeader(Exchange.HTTP_PATH)
                .id("Prepare Headers")
                .setHeader(Exchange.HTTP_METHOD, constant("PUT"))
                .id("Prepare PUT HTTP operation")
                .toD("http4://"+elibilityURL+"/customer-product-service-eligibility/${header.sdRefId}/customer-eligibility-assessment/${header.sessionref}/update?bridgeEndpoint=true")
                .id("Invoke Update Product Usage")
                .bean(TransformerBean.class,"prepareOfferInitiationResponse")
                .id("Prepare final response");




    }
}
