/*
 * Account Recovery
 * This service domain handles the restructuring of a distressed account (loan) after standard recovery
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.accountrecovery.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BQPlanningRetrieveOutputModelPlanningInstanceAnalysis
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-07T18:27:41.474305+02:00[Europe/Madrid]")
public class BQPlanningRetrieveOutputModelPlanningInstanceAnalysis {
  @SerializedName("planningInstanceAnalysisRecord")
  private Object planningInstanceAnalysisRecord = null;

  @SerializedName("planningInstanceAnalysisReportType")
  private String planningInstanceAnalysisReportType = null;

  @SerializedName("planningInstanceAnalysisParameters")
  private String planningInstanceAnalysisParameters = null;

  @SerializedName("planningInstanceAnalysisReport")
  private Object planningInstanceAnalysisReport = null;

  public BQPlanningRetrieveOutputModelPlanningInstanceAnalysis planningInstanceAnalysisRecord(Object planningInstanceAnalysisRecord) {
    this.planningInstanceAnalysisRecord = planningInstanceAnalysisRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The inputs and results of the instance analysis that can be on-going, periodic and actual and projected 
   * @return planningInstanceAnalysisRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The inputs and results of the instance analysis that can be on-going, periodic and actual and projected ")
  public Object getPlanningInstanceAnalysisRecord() {
    return planningInstanceAnalysisRecord;
  }

  public void setPlanningInstanceAnalysisRecord(Object planningInstanceAnalysisRecord) {
    this.planningInstanceAnalysisRecord = planningInstanceAnalysisRecord;
  }

  public BQPlanningRetrieveOutputModelPlanningInstanceAnalysis planningInstanceAnalysisReportType(String planningInstanceAnalysisReportType) {
    this.planningInstanceAnalysisReportType = planningInstanceAnalysisReportType;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Code  general-info: The type of external performance analysis report available 
   * @return planningInstanceAnalysisReportType
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Code  general-info: The type of external performance analysis report available ")
  public String getPlanningInstanceAnalysisReportType() {
    return planningInstanceAnalysisReportType;
  }

  public void setPlanningInstanceAnalysisReportType(String planningInstanceAnalysisReportType) {
    this.planningInstanceAnalysisReportType = planningInstanceAnalysisReportType;
  }

  public BQPlanningRetrieveOutputModelPlanningInstanceAnalysis planningInstanceAnalysisParameters(String planningInstanceAnalysisParameters) {
    this.planningInstanceAnalysisParameters = planningInstanceAnalysisParameters;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The selection parameters for the analysis (e.g. period, algorithm type) 
   * @return planningInstanceAnalysisParameters
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The selection parameters for the analysis (e.g. period, algorithm type) ")
  public String getPlanningInstanceAnalysisParameters() {
    return planningInstanceAnalysisParameters;
  }

  public void setPlanningInstanceAnalysisParameters(String planningInstanceAnalysisParameters) {
    this.planningInstanceAnalysisParameters = planningInstanceAnalysisParameters;
  }

  public BQPlanningRetrieveOutputModelPlanningInstanceAnalysis planningInstanceAnalysisReport(Object planningInstanceAnalysisReport) {
    this.planningInstanceAnalysisReport = planningInstanceAnalysisReport;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The external analysis report in any suitable form including selection filters where appropriate 
   * @return planningInstanceAnalysisReport
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The external analysis report in any suitable form including selection filters where appropriate ")
  public Object getPlanningInstanceAnalysisReport() {
    return planningInstanceAnalysisReport;
  }

  public void setPlanningInstanceAnalysisReport(Object planningInstanceAnalysisReport) {
    this.planningInstanceAnalysisReport = planningInstanceAnalysisReport;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BQPlanningRetrieveOutputModelPlanningInstanceAnalysis bqPlanningRetrieveOutputModelPlanningInstanceAnalysis = (BQPlanningRetrieveOutputModelPlanningInstanceAnalysis) o;
    return Objects.equals(this.planningInstanceAnalysisRecord, bqPlanningRetrieveOutputModelPlanningInstanceAnalysis.planningInstanceAnalysisRecord) &&
        Objects.equals(this.planningInstanceAnalysisReportType, bqPlanningRetrieveOutputModelPlanningInstanceAnalysis.planningInstanceAnalysisReportType) &&
        Objects.equals(this.planningInstanceAnalysisParameters, bqPlanningRetrieveOutputModelPlanningInstanceAnalysis.planningInstanceAnalysisParameters) &&
        Objects.equals(this.planningInstanceAnalysisReport, bqPlanningRetrieveOutputModelPlanningInstanceAnalysis.planningInstanceAnalysisReport);
  }

  @Override
  public int hashCode() {
    return Objects.hash(planningInstanceAnalysisRecord, planningInstanceAnalysisReportType, planningInstanceAnalysisParameters, planningInstanceAnalysisReport);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BQPlanningRetrieveOutputModelPlanningInstanceAnalysis {\n");
    
    sb.append("    planningInstanceAnalysisRecord: ").append(toIndentedString(planningInstanceAnalysisRecord)).append("\n");
    sb.append("    planningInstanceAnalysisReportType: ").append(toIndentedString(planningInstanceAnalysisReportType)).append("\n");
    sb.append("    planningInstanceAnalysisParameters: ").append(toIndentedString(planningInstanceAnalysisParameters)).append("\n");
    sb.append("    planningInstanceAnalysisReport: ").append(toIndentedString(planningInstanceAnalysisReport)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
