/*
 * Account Recovery
 * This service domain handles the restructuring of a distressed account (loan) after standard recovery
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.accountrecovery.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BQPlanningUpdateOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-07T18:27:41.474305+02:00[Europe/Madrid]")
public class BQPlanningUpdateOutputModel {
  @SerializedName("planningInstanceRecord")
  private Object planningInstanceRecord = null;

  @SerializedName("planningUpdateActionTaskReference")
  private String planningUpdateActionTaskReference = null;

  @SerializedName("planningUpdateActionTaskRecord")
  private Object planningUpdateActionTaskRecord = null;

  @SerializedName("updateResponseRecord")
  private Object updateResponseRecord = null;

  public BQPlanningUpdateOutputModel planningInstanceRecord(Object planningInstanceRecord) {
    this.planningInstanceRecord = planningInstanceRecord;
    return this;
  }

   /**
   * Get planningInstanceRecord
   * @return planningInstanceRecord
  **/
  @Schema(description = "")
  public Object getPlanningInstanceRecord() {
    return planningInstanceRecord;
  }

  public void setPlanningInstanceRecord(Object planningInstanceRecord) {
    this.planningInstanceRecord = planningInstanceRecord;
  }

  public BQPlanningUpdateOutputModel planningUpdateActionTaskReference(String planningUpdateActionTaskReference) {
    this.planningUpdateActionTaskReference = planningUpdateActionTaskReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to an update service call 
   * @return planningUpdateActionTaskReference
  **/
  @Schema(example = "ARPUATR766513", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to an update service call ")
  public String getPlanningUpdateActionTaskReference() {
    return planningUpdateActionTaskReference;
  }

  public void setPlanningUpdateActionTaskReference(String planningUpdateActionTaskReference) {
    this.planningUpdateActionTaskReference = planningUpdateActionTaskReference;
  }

  public BQPlanningUpdateOutputModel planningUpdateActionTaskRecord(Object planningUpdateActionTaskRecord) {
    this.planningUpdateActionTaskRecord = planningUpdateActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record 
   * @return planningUpdateActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The update service call consolidated processing record ")
  public Object getPlanningUpdateActionTaskRecord() {
    return planningUpdateActionTaskRecord;
  }

  public void setPlanningUpdateActionTaskRecord(Object planningUpdateActionTaskRecord) {
    this.planningUpdateActionTaskRecord = planningUpdateActionTaskRecord;
  }

  public BQPlanningUpdateOutputModel updateResponseRecord(Object updateResponseRecord) {
    this.updateResponseRecord = updateResponseRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: Details of the Update action service response 
   * @return updateResponseRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: Details of the Update action service response ")
  public Object getUpdateResponseRecord() {
    return updateResponseRecord;
  }

  public void setUpdateResponseRecord(Object updateResponseRecord) {
    this.updateResponseRecord = updateResponseRecord;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BQPlanningUpdateOutputModel bqPlanningUpdateOutputModel = (BQPlanningUpdateOutputModel) o;
    return Objects.equals(this.planningInstanceRecord, bqPlanningUpdateOutputModel.planningInstanceRecord) &&
        Objects.equals(this.planningUpdateActionTaskReference, bqPlanningUpdateOutputModel.planningUpdateActionTaskReference) &&
        Objects.equals(this.planningUpdateActionTaskRecord, bqPlanningUpdateOutputModel.planningUpdateActionTaskRecord) &&
        Objects.equals(this.updateResponseRecord, bqPlanningUpdateOutputModel.updateResponseRecord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(planningInstanceRecord, planningUpdateActionTaskReference, planningUpdateActionTaskRecord, updateResponseRecord);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BQPlanningUpdateOutputModel {\n");
    
    sb.append("    planningInstanceRecord: ").append(toIndentedString(planningInstanceRecord)).append("\n");
    sb.append("    planningUpdateActionTaskReference: ").append(toIndentedString(planningUpdateActionTaskReference)).append("\n");
    sb.append("    planningUpdateActionTaskRecord: ").append(toIndentedString(planningUpdateActionTaskRecord)).append("\n");
    sb.append("    updateResponseRecord: ").append(toIndentedString(updateResponseRecord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
