/*
 * Account Recovery
 * This service domain handles the restructuring of a distressed account (loan) after standard recovery
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.accountrecovery.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * BQRestructuringRetrieveOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-07T18:27:41.474305+02:00[Europe/Madrid]")
public class BQRestructuringRetrieveOutputModel {
  @SerializedName("accountRecoveryProcedureInstanceRecord")
  private Object accountRecoveryProcedureInstanceRecord = null;

  @SerializedName("restructuringInstanceRecord")
  private Object restructuringInstanceRecord = null;

  @SerializedName("restructuringRetrieveActionTaskReference")
  private String restructuringRetrieveActionTaskReference = null;

  @SerializedName("restructuringRetrieveActionTaskRecord")
  private Object restructuringRetrieveActionTaskRecord = null;

  @SerializedName("restructuringRetrieveActionResponse")
  private String restructuringRetrieveActionResponse = null;

  @SerializedName("restructuringInstanceReport")
  private Object restructuringInstanceReport = null;

  @SerializedName("restructuringInstanceAnalysis")
  private Object restructuringInstanceAnalysis = null;

  public BQRestructuringRetrieveOutputModel accountRecoveryProcedureInstanceRecord(Object accountRecoveryProcedureInstanceRecord) {
    this.accountRecoveryProcedureInstanceRecord = accountRecoveryProcedureInstanceRecord;
    return this;
  }

   /**
   * Get accountRecoveryProcedureInstanceRecord
   * @return accountRecoveryProcedureInstanceRecord
  **/
  @Schema(description = "")
  public Object getAccountRecoveryProcedureInstanceRecord() {
    return accountRecoveryProcedureInstanceRecord;
  }

  public void setAccountRecoveryProcedureInstanceRecord(Object accountRecoveryProcedureInstanceRecord) {
    this.accountRecoveryProcedureInstanceRecord = accountRecoveryProcedureInstanceRecord;
  }

  public BQRestructuringRetrieveOutputModel restructuringInstanceRecord(Object restructuringInstanceRecord) {
    this.restructuringInstanceRecord = restructuringInstanceRecord;
    return this;
  }

   /**
   * Get restructuringInstanceRecord
   * @return restructuringInstanceRecord
  **/
  @Schema(description = "")
  public Object getRestructuringInstanceRecord() {
    return restructuringInstanceRecord;
  }

  public void setRestructuringInstanceRecord(Object restructuringInstanceRecord) {
    this.restructuringInstanceRecord = restructuringInstanceRecord;
  }

  public BQRestructuringRetrieveOutputModel restructuringRetrieveActionTaskReference(String restructuringRetrieveActionTaskReference) {
    this.restructuringRetrieveActionTaskReference = restructuringRetrieveActionTaskReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Restructuring instance retrieve service call 
   * @return restructuringRetrieveActionTaskReference
  **/
  @Schema(example = "RRATR788803", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Restructuring instance retrieve service call ")
  public String getRestructuringRetrieveActionTaskReference() {
    return restructuringRetrieveActionTaskReference;
  }

  public void setRestructuringRetrieveActionTaskReference(String restructuringRetrieveActionTaskReference) {
    this.restructuringRetrieveActionTaskReference = restructuringRetrieveActionTaskReference;
  }

  public BQRestructuringRetrieveOutputModel restructuringRetrieveActionTaskRecord(Object restructuringRetrieveActionTaskRecord) {
    this.restructuringRetrieveActionTaskRecord = restructuringRetrieveActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record 
   * @return restructuringRetrieveActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record ")
  public Object getRestructuringRetrieveActionTaskRecord() {
    return restructuringRetrieveActionTaskRecord;
  }

  public void setRestructuringRetrieveActionTaskRecord(Object restructuringRetrieveActionTaskRecord) {
    this.restructuringRetrieveActionTaskRecord = restructuringRetrieveActionTaskRecord;
  }

  public BQRestructuringRetrieveOutputModel restructuringRetrieveActionResponse(String restructuringRetrieveActionResponse) {
    this.restructuringRetrieveActionResponse = restructuringRetrieveActionResponse;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) 
   * @return restructuringRetrieveActionResponse
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) ")
  public String getRestructuringRetrieveActionResponse() {
    return restructuringRetrieveActionResponse;
  }

  public void setRestructuringRetrieveActionResponse(String restructuringRetrieveActionResponse) {
    this.restructuringRetrieveActionResponse = restructuringRetrieveActionResponse;
  }

  public BQRestructuringRetrieveOutputModel restructuringInstanceReport(Object restructuringInstanceReport) {
    this.restructuringInstanceReport = restructuringInstanceReport;
    return this;
  }

   /**
   * Get restructuringInstanceReport
   * @return restructuringInstanceReport
  **/
  @Schema(description = "")
  public Object getRestructuringInstanceReport() {
    return restructuringInstanceReport;
  }

  public void setRestructuringInstanceReport(Object restructuringInstanceReport) {
    this.restructuringInstanceReport = restructuringInstanceReport;
  }

  public BQRestructuringRetrieveOutputModel restructuringInstanceAnalysis(Object restructuringInstanceAnalysis) {
    this.restructuringInstanceAnalysis = restructuringInstanceAnalysis;
    return this;
  }

   /**
   * Get restructuringInstanceAnalysis
   * @return restructuringInstanceAnalysis
  **/
  @Schema(description = "")
  public Object getRestructuringInstanceAnalysis() {
    return restructuringInstanceAnalysis;
  }

  public void setRestructuringInstanceAnalysis(Object restructuringInstanceAnalysis) {
    this.restructuringInstanceAnalysis = restructuringInstanceAnalysis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BQRestructuringRetrieveOutputModel bqRestructuringRetrieveOutputModel = (BQRestructuringRetrieveOutputModel) o;
    return Objects.equals(this.accountRecoveryProcedureInstanceRecord, bqRestructuringRetrieveOutputModel.accountRecoveryProcedureInstanceRecord) &&
        Objects.equals(this.restructuringInstanceRecord, bqRestructuringRetrieveOutputModel.restructuringInstanceRecord) &&
        Objects.equals(this.restructuringRetrieveActionTaskReference, bqRestructuringRetrieveOutputModel.restructuringRetrieveActionTaskReference) &&
        Objects.equals(this.restructuringRetrieveActionTaskRecord, bqRestructuringRetrieveOutputModel.restructuringRetrieveActionTaskRecord) &&
        Objects.equals(this.restructuringRetrieveActionResponse, bqRestructuringRetrieveOutputModel.restructuringRetrieveActionResponse) &&
        Objects.equals(this.restructuringInstanceReport, bqRestructuringRetrieveOutputModel.restructuringInstanceReport) &&
        Objects.equals(this.restructuringInstanceAnalysis, bqRestructuringRetrieveOutputModel.restructuringInstanceAnalysis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountRecoveryProcedureInstanceRecord, restructuringInstanceRecord, restructuringRetrieveActionTaskReference, restructuringRetrieveActionTaskRecord, restructuringRetrieveActionResponse, restructuringInstanceReport, restructuringInstanceAnalysis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BQRestructuringRetrieveOutputModel {\n");
    
    sb.append("    accountRecoveryProcedureInstanceRecord: ").append(toIndentedString(accountRecoveryProcedureInstanceRecord)).append("\n");
    sb.append("    restructuringInstanceRecord: ").append(toIndentedString(restructuringInstanceRecord)).append("\n");
    sb.append("    restructuringRetrieveActionTaskReference: ").append(toIndentedString(restructuringRetrieveActionTaskReference)).append("\n");
    sb.append("    restructuringRetrieveActionTaskRecord: ").append(toIndentedString(restructuringRetrieveActionTaskRecord)).append("\n");
    sb.append("    restructuringRetrieveActionResponse: ").append(toIndentedString(restructuringRetrieveActionResponse)).append("\n");
    sb.append("    restructuringInstanceReport: ").append(toIndentedString(restructuringInstanceReport)).append("\n");
    sb.append("    restructuringInstanceAnalysis: ").append(toIndentedString(restructuringInstanceAnalysis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
