/*
 * Account Recovery
 * This service domain handles the restructuring of a distressed account (loan) after standard recovery
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.accountrecovery.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-07T18:27:41.474305+02:00[Europe/Madrid]")
public class CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord {
  @SerializedName("linkedProductInstanceReference")
  private String linkedProductInstanceReference = null;

  @SerializedName("dateType")
  private Object dateType = null;

  @SerializedName("accountStatus")
  private String accountStatus = null;

  @SerializedName("accountRecoveryCaseWorkProducts")
  private Object accountRecoveryCaseWorkProducts = null;

  @SerializedName("accountRecoveryCaseResolutionSchedule")
  private String accountRecoveryCaseResolutionSchedule = null;

  @SerializedName("accountRecoveryCaseStatus")
  private String accountRecoveryCaseStatus = null;

  public CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord linkedProductInstanceReference(String linkedProductInstanceReference) {
    this.linkedProductInstanceReference = linkedProductInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Refers to any new/replacement product established during the recovery/restructuring process 
   * @return linkedProductInstanceReference
  **/
  @Schema(example = "767774", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Refers to any new/replacement product established during the recovery/restructuring process ")
  public String getLinkedProductInstanceReference() {
    return linkedProductInstanceReference;
  }

  public void setLinkedProductInstanceReference(String linkedProductInstanceReference) {
    this.linkedProductInstanceReference = linkedProductInstanceReference;
  }

  public CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord dateType(Object dateType) {
    this.dateType = dateType;
    return this;
  }

   /**
   * Get dateType
   * @return dateType
  **/
  @Schema(description = "")
  public Object getDateType() {
    return dateType;
  }

  public void setDateType(Object dateType) {
    this.dateType = dateType;
  }

  public CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord accountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Status of the recovery account (e.g. pre-opened, active, dormant, pending for closing, blocked) 
   * @return accountStatus
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Status of the recovery account (e.g. pre-opened, active, dormant, pending for closing, blocked) ")
  public String getAccountStatus() {
    return accountStatus;
  }

  public void setAccountStatus(String accountStatus) {
    this.accountStatus = accountStatus;
  }

  public CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord accountRecoveryCaseWorkProducts(Object accountRecoveryCaseWorkProducts) {
    this.accountRecoveryCaseWorkProducts = accountRecoveryCaseWorkProducts;
    return this;
  }

   /**
   * Get accountRecoveryCaseWorkProducts
   * @return accountRecoveryCaseWorkProducts
  **/
  @Schema(description = "")
  public Object getAccountRecoveryCaseWorkProducts() {
    return accountRecoveryCaseWorkProducts;
  }

  public void setAccountRecoveryCaseWorkProducts(Object accountRecoveryCaseWorkProducts) {
    this.accountRecoveryCaseWorkProducts = accountRecoveryCaseWorkProducts;
  }

  public CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord accountRecoveryCaseResolutionSchedule(String accountRecoveryCaseResolutionSchedule) {
    this.accountRecoveryCaseResolutionSchedule = accountRecoveryCaseResolutionSchedule;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Target and actual dates for processing/resolution 
   * @return accountRecoveryCaseResolutionSchedule
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Target and actual dates for processing/resolution ")
  public String getAccountRecoveryCaseResolutionSchedule() {
    return accountRecoveryCaseResolutionSchedule;
  }

  public void setAccountRecoveryCaseResolutionSchedule(String accountRecoveryCaseResolutionSchedule) {
    this.accountRecoveryCaseResolutionSchedule = accountRecoveryCaseResolutionSchedule;
  }

  public CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord accountRecoveryCaseStatus(String accountRecoveryCaseStatus) {
    this.accountRecoveryCaseStatus = accountRecoveryCaseStatus;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The status of the recovery case (e.g. in assessment, write-down, planning, negotiation, restructuring) 
   * @return accountRecoveryCaseStatus
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The status of the recovery case (e.g. in assessment, write-down, planning, negotiation, restructuring) ")
  public String getAccountRecoveryCaseStatus() {
    return accountRecoveryCaseStatus;
  }

  public void setAccountRecoveryCaseStatus(String accountRecoveryCaseStatus) {
    this.accountRecoveryCaseStatus = accountRecoveryCaseStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord crAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord = (CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord) o;
    return Objects.equals(this.linkedProductInstanceReference, crAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord.linkedProductInstanceReference) &&
        Objects.equals(this.dateType, crAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord.dateType) &&
        Objects.equals(this.accountStatus, crAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord.accountStatus) &&
        Objects.equals(this.accountRecoveryCaseWorkProducts, crAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord.accountRecoveryCaseWorkProducts) &&
        Objects.equals(this.accountRecoveryCaseResolutionSchedule, crAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord.accountRecoveryCaseResolutionSchedule) &&
        Objects.equals(this.accountRecoveryCaseStatus, crAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord.accountRecoveryCaseStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkedProductInstanceReference, dateType, accountStatus, accountRecoveryCaseWorkProducts, accountRecoveryCaseResolutionSchedule, accountRecoveryCaseStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CRAccountRecoveryProcedureInitiateOutputModelAccountRecoveryProcedureInstanceRecord {\n");
    
    sb.append("    linkedProductInstanceReference: ").append(toIndentedString(linkedProductInstanceReference)).append("\n");
    sb.append("    dateType: ").append(toIndentedString(dateType)).append("\n");
    sb.append("    accountStatus: ").append(toIndentedString(accountStatus)).append("\n");
    sb.append("    accountRecoveryCaseWorkProducts: ").append(toIndentedString(accountRecoveryCaseWorkProducts)).append("\n");
    sb.append("    accountRecoveryCaseResolutionSchedule: ").append(toIndentedString(accountRecoveryCaseResolutionSchedule)).append("\n");
    sb.append("    accountRecoveryCaseStatus: ").append(toIndentedString(accountRecoveryCaseStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
