/*
 * Account Recovery
 * This service domain handles the restructuring of a distressed account (loan) after standard recovery
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.accountrecovery.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CRAccountRecoveryProcedureInitiateOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-07T18:27:41.474305+02:00[Europe/Madrid]")
public class CRAccountRecoveryProcedureInitiateOutputModel {
  @SerializedName("accountRecoveryProcedureInstanceReference")
  private String accountRecoveryProcedureInstanceReference = null;

  @SerializedName("accountRecoveryProcedureInitiateActionReference")
  private String accountRecoveryProcedureInitiateActionReference = null;

  @SerializedName("accountRecoveryProcedureInitiateActionRecord")
  private Object accountRecoveryProcedureInitiateActionRecord = null;

  @SerializedName("accountRecoveryProcedureInstanceStatus")
  private String accountRecoveryProcedureInstanceStatus = null;

  @SerializedName("accountRecoveryProcedureInstanceRecord")
  private Object accountRecoveryProcedureInstanceRecord = null;

  public CRAccountRecoveryProcedureInitiateOutputModel accountRecoveryProcedureInstanceReference(String accountRecoveryProcedureInstanceReference) {
    this.accountRecoveryProcedureInstanceReference = accountRecoveryProcedureInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Account Recovery Procedure instance 
   * @return accountRecoveryProcedureInstanceReference
  **/
  @Schema(example = "ARPIR716835", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Account Recovery Procedure instance ")
  public String getAccountRecoveryProcedureInstanceReference() {
    return accountRecoveryProcedureInstanceReference;
  }

  public void setAccountRecoveryProcedureInstanceReference(String accountRecoveryProcedureInstanceReference) {
    this.accountRecoveryProcedureInstanceReference = accountRecoveryProcedureInstanceReference;
  }

  public CRAccountRecoveryProcedureInitiateOutputModel accountRecoveryProcedureInitiateActionReference(String accountRecoveryProcedureInitiateActionReference) {
    this.accountRecoveryProcedureInitiateActionReference = accountRecoveryProcedureInitiateActionReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to an Initiate service call 
   * @return accountRecoveryProcedureInitiateActionReference
  **/
  @Schema(example = "ARPIAR788634", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to an Initiate service call ")
  public String getAccountRecoveryProcedureInitiateActionReference() {
    return accountRecoveryProcedureInitiateActionReference;
  }

  public void setAccountRecoveryProcedureInitiateActionReference(String accountRecoveryProcedureInitiateActionReference) {
    this.accountRecoveryProcedureInitiateActionReference = accountRecoveryProcedureInitiateActionReference;
  }

  public CRAccountRecoveryProcedureInitiateOutputModel accountRecoveryProcedureInitiateActionRecord(Object accountRecoveryProcedureInitiateActionRecord) {
    this.accountRecoveryProcedureInitiateActionRecord = accountRecoveryProcedureInitiateActionRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The Initiate service call input and output record 
   * @return accountRecoveryProcedureInitiateActionRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The Initiate service call input and output record ")
  public Object getAccountRecoveryProcedureInitiateActionRecord() {
    return accountRecoveryProcedureInitiateActionRecord;
  }

  public void setAccountRecoveryProcedureInitiateActionRecord(Object accountRecoveryProcedureInitiateActionRecord) {
    this.accountRecoveryProcedureInitiateActionRecord = accountRecoveryProcedureInitiateActionRecord;
  }

  public CRAccountRecoveryProcedureInitiateOutputModel accountRecoveryProcedureInstanceStatus(String accountRecoveryProcedureInstanceStatus) {
    this.accountRecoveryProcedureInstanceStatus = accountRecoveryProcedureInstanceStatus;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The status of the Account Recovery Procedure instance (e.g. initialised, pending, active) 
   * @return accountRecoveryProcedureInstanceStatus
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The status of the Account Recovery Procedure instance (e.g. initialised, pending, active) ")
  public String getAccountRecoveryProcedureInstanceStatus() {
    return accountRecoveryProcedureInstanceStatus;
  }

  public void setAccountRecoveryProcedureInstanceStatus(String accountRecoveryProcedureInstanceStatus) {
    this.accountRecoveryProcedureInstanceStatus = accountRecoveryProcedureInstanceStatus;
  }

  public CRAccountRecoveryProcedureInitiateOutputModel accountRecoveryProcedureInstanceRecord(Object accountRecoveryProcedureInstanceRecord) {
    this.accountRecoveryProcedureInstanceRecord = accountRecoveryProcedureInstanceRecord;
    return this;
  }

   /**
   * Get accountRecoveryProcedureInstanceRecord
   * @return accountRecoveryProcedureInstanceRecord
  **/
  @Schema(description = "")
  public Object getAccountRecoveryProcedureInstanceRecord() {
    return accountRecoveryProcedureInstanceRecord;
  }

  public void setAccountRecoveryProcedureInstanceRecord(Object accountRecoveryProcedureInstanceRecord) {
    this.accountRecoveryProcedureInstanceRecord = accountRecoveryProcedureInstanceRecord;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CRAccountRecoveryProcedureInitiateOutputModel crAccountRecoveryProcedureInitiateOutputModel = (CRAccountRecoveryProcedureInitiateOutputModel) o;
    return Objects.equals(this.accountRecoveryProcedureInstanceReference, crAccountRecoveryProcedureInitiateOutputModel.accountRecoveryProcedureInstanceReference) &&
        Objects.equals(this.accountRecoveryProcedureInitiateActionReference, crAccountRecoveryProcedureInitiateOutputModel.accountRecoveryProcedureInitiateActionReference) &&
        Objects.equals(this.accountRecoveryProcedureInitiateActionRecord, crAccountRecoveryProcedureInitiateOutputModel.accountRecoveryProcedureInitiateActionRecord) &&
        Objects.equals(this.accountRecoveryProcedureInstanceStatus, crAccountRecoveryProcedureInitiateOutputModel.accountRecoveryProcedureInstanceStatus) &&
        Objects.equals(this.accountRecoveryProcedureInstanceRecord, crAccountRecoveryProcedureInitiateOutputModel.accountRecoveryProcedureInstanceRecord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountRecoveryProcedureInstanceReference, accountRecoveryProcedureInitiateActionReference, accountRecoveryProcedureInitiateActionRecord, accountRecoveryProcedureInstanceStatus, accountRecoveryProcedureInstanceRecord);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CRAccountRecoveryProcedureInitiateOutputModel {\n");
    
    sb.append("    accountRecoveryProcedureInstanceReference: ").append(toIndentedString(accountRecoveryProcedureInstanceReference)).append("\n");
    sb.append("    accountRecoveryProcedureInitiateActionReference: ").append(toIndentedString(accountRecoveryProcedureInitiateActionReference)).append("\n");
    sb.append("    accountRecoveryProcedureInitiateActionRecord: ").append(toIndentedString(accountRecoveryProcedureInitiateActionRecord)).append("\n");
    sb.append("    accountRecoveryProcedureInstanceStatus: ").append(toIndentedString(accountRecoveryProcedureInstanceStatus)).append("\n");
    sb.append("    accountRecoveryProcedureInstanceRecord: ").append(toIndentedString(accountRecoveryProcedureInstanceRecord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
