apiVersion: mercury.redhat.io/v1alpha1
kind: ServiceDomain
metadata:
  name: customer-offer
  labels:
    app: example
spec:
  businessImage: quay.io/ecosystem-appeng/customer-offer-example:1.0.2-SNAPSHOT
  serviceDomainInfra: my-first-sdi
  type: CustomerOffer
  expose:
    - http