apiVersion: mercury.redhat.io/v1alpha1
kind: ServiceDomain
metadata:
  name: customer-credit-rating
  labels:
    app: example
spec:
  businessImage: quay.io/ecosystem-appeng/customer-credit-rating-example:1.0.2-SNAPSHOT
  serviceDomainInfra: my-first-sdi
  type: CustomerCreditRating
  expose:
    - http