apiVersion: mercury.redhat.io/v1alpha1
kind: ServiceDomain
metadata:
  name: party-routing-profile
  labels:
    app: example
spec:
  businessImage: quay.io/ecosystem-appeng/party-routing-profile-example:1.0.1-SNAPSHOT
  serviceDomainCluster: my-first-sdc
  type: PartyRoutingProfile
  expose:
    - http