/*
 * Customer Credit Rating
 * This service domain maintains and administers the bank's credit assessment for customers.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customercreditrating.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CRCustomerCreditRatingStateRetrieveOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-03T15:34:54.132884+02:00[Europe/Madrid]")
public class CRCustomerCreditRatingStateRetrieveOutputModel {
  @SerializedName("customerCreditRatingStateInstanceRecord")
  private Object customerCreditRatingStateInstanceRecord = null;

  @SerializedName("customerCreditRatingStateRetrieveActionTaskReference")
  private String customerCreditRatingStateRetrieveActionTaskReference = null;

  @SerializedName("customerCreditRatingStateRetrieveActionTaskRecord")
  private Object customerCreditRatingStateRetrieveActionTaskRecord = null;

  @SerializedName("customerCreditRatingStateRetrieveActionResponse")
  private String customerCreditRatingStateRetrieveActionResponse = null;

  @SerializedName("customerCreditRatingStateInstanceReportRecord")
  private Object customerCreditRatingStateInstanceReportRecord = null;

  @SerializedName("customerCreditRatingStateInstanceAnalysis")
  private Object customerCreditRatingStateInstanceAnalysis = null;

  public CRCustomerCreditRatingStateRetrieveOutputModel customerCreditRatingStateInstanceRecord(Object customerCreditRatingStateInstanceRecord) {
    this.customerCreditRatingStateInstanceRecord = customerCreditRatingStateInstanceRecord;
    return this;
  }

   /**
   * Get customerCreditRatingStateInstanceRecord
   * @return customerCreditRatingStateInstanceRecord
  **/
  @Schema(description = "")
  public Object getCustomerCreditRatingStateInstanceRecord() {
    return customerCreditRatingStateInstanceRecord;
  }

  public void setCustomerCreditRatingStateInstanceRecord(Object customerCreditRatingStateInstanceRecord) {
    this.customerCreditRatingStateInstanceRecord = customerCreditRatingStateInstanceRecord;
  }

  public CRCustomerCreditRatingStateRetrieveOutputModel customerCreditRatingStateRetrieveActionTaskReference(String customerCreditRatingStateRetrieveActionTaskReference) {
    this.customerCreditRatingStateRetrieveActionTaskReference = customerCreditRatingStateRetrieveActionTaskReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Customer Credit Rating State instance retrieve service call 
   * @return customerCreditRatingStateRetrieveActionTaskReference
  **/
  @Schema(example = "CCRSRATR743660", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a Customer Credit Rating State instance retrieve service call ")
  public String getCustomerCreditRatingStateRetrieveActionTaskReference() {
    return customerCreditRatingStateRetrieveActionTaskReference;
  }

  public void setCustomerCreditRatingStateRetrieveActionTaskReference(String customerCreditRatingStateRetrieveActionTaskReference) {
    this.customerCreditRatingStateRetrieveActionTaskReference = customerCreditRatingStateRetrieveActionTaskReference;
  }

  public CRCustomerCreditRatingStateRetrieveOutputModel customerCreditRatingStateRetrieveActionTaskRecord(Object customerCreditRatingStateRetrieveActionTaskRecord) {
    this.customerCreditRatingStateRetrieveActionTaskRecord = customerCreditRatingStateRetrieveActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record 
   * @return customerCreditRatingStateRetrieveActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The retrieve service call consolidated processing record ")
  public Object getCustomerCreditRatingStateRetrieveActionTaskRecord() {
    return customerCreditRatingStateRetrieveActionTaskRecord;
  }

  public void setCustomerCreditRatingStateRetrieveActionTaskRecord(Object customerCreditRatingStateRetrieveActionTaskRecord) {
    this.customerCreditRatingStateRetrieveActionTaskRecord = customerCreditRatingStateRetrieveActionTaskRecord;
  }

  public CRCustomerCreditRatingStateRetrieveOutputModel customerCreditRatingStateRetrieveActionResponse(String customerCreditRatingStateRetrieveActionResponse) {
    this.customerCreditRatingStateRetrieveActionResponse = customerCreditRatingStateRetrieveActionResponse;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) 
   * @return customerCreditRatingStateRetrieveActionResponse
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: Details of the retrieve action service response (lists returned reports) ")
  public String getCustomerCreditRatingStateRetrieveActionResponse() {
    return customerCreditRatingStateRetrieveActionResponse;
  }

  public void setCustomerCreditRatingStateRetrieveActionResponse(String customerCreditRatingStateRetrieveActionResponse) {
    this.customerCreditRatingStateRetrieveActionResponse = customerCreditRatingStateRetrieveActionResponse;
  }

  public CRCustomerCreditRatingStateRetrieveOutputModel customerCreditRatingStateInstanceReportRecord(Object customerCreditRatingStateInstanceReportRecord) {
    this.customerCreditRatingStateInstanceReportRecord = customerCreditRatingStateInstanceReportRecord;
    return this;
  }

   /**
   * Get customerCreditRatingStateInstanceReportRecord
   * @return customerCreditRatingStateInstanceReportRecord
  **/
  @Schema(description = "")
  public Object getCustomerCreditRatingStateInstanceReportRecord() {
    return customerCreditRatingStateInstanceReportRecord;
  }

  public void setCustomerCreditRatingStateInstanceReportRecord(Object customerCreditRatingStateInstanceReportRecord) {
    this.customerCreditRatingStateInstanceReportRecord = customerCreditRatingStateInstanceReportRecord;
  }

  public CRCustomerCreditRatingStateRetrieveOutputModel customerCreditRatingStateInstanceAnalysis(Object customerCreditRatingStateInstanceAnalysis) {
    this.customerCreditRatingStateInstanceAnalysis = customerCreditRatingStateInstanceAnalysis;
    return this;
  }

   /**
   * Get customerCreditRatingStateInstanceAnalysis
   * @return customerCreditRatingStateInstanceAnalysis
  **/
  @Schema(description = "")
  public Object getCustomerCreditRatingStateInstanceAnalysis() {
    return customerCreditRatingStateInstanceAnalysis;
  }

  public void setCustomerCreditRatingStateInstanceAnalysis(Object customerCreditRatingStateInstanceAnalysis) {
    this.customerCreditRatingStateInstanceAnalysis = customerCreditRatingStateInstanceAnalysis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CRCustomerCreditRatingStateRetrieveOutputModel crCustomerCreditRatingStateRetrieveOutputModel = (CRCustomerCreditRatingStateRetrieveOutputModel) o;
    return Objects.equals(this.customerCreditRatingStateInstanceRecord, crCustomerCreditRatingStateRetrieveOutputModel.customerCreditRatingStateInstanceRecord) &&
        Objects.equals(this.customerCreditRatingStateRetrieveActionTaskReference, crCustomerCreditRatingStateRetrieveOutputModel.customerCreditRatingStateRetrieveActionTaskReference) &&
        Objects.equals(this.customerCreditRatingStateRetrieveActionTaskRecord, crCustomerCreditRatingStateRetrieveOutputModel.customerCreditRatingStateRetrieveActionTaskRecord) &&
        Objects.equals(this.customerCreditRatingStateRetrieveActionResponse, crCustomerCreditRatingStateRetrieveOutputModel.customerCreditRatingStateRetrieveActionResponse) &&
        Objects.equals(this.customerCreditRatingStateInstanceReportRecord, crCustomerCreditRatingStateRetrieveOutputModel.customerCreditRatingStateInstanceReportRecord) &&
        Objects.equals(this.customerCreditRatingStateInstanceAnalysis, crCustomerCreditRatingStateRetrieveOutputModel.customerCreditRatingStateInstanceAnalysis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerCreditRatingStateInstanceRecord, customerCreditRatingStateRetrieveActionTaskReference, customerCreditRatingStateRetrieveActionTaskRecord, customerCreditRatingStateRetrieveActionResponse, customerCreditRatingStateInstanceReportRecord, customerCreditRatingStateInstanceAnalysis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CRCustomerCreditRatingStateRetrieveOutputModel {\n");
    
    sb.append("    customerCreditRatingStateInstanceRecord: ").append(toIndentedString(customerCreditRatingStateInstanceRecord)).append("\n");
    sb.append("    customerCreditRatingStateRetrieveActionTaskReference: ").append(toIndentedString(customerCreditRatingStateRetrieveActionTaskReference)).append("\n");
    sb.append("    customerCreditRatingStateRetrieveActionTaskRecord: ").append(toIndentedString(customerCreditRatingStateRetrieveActionTaskRecord)).append("\n");
    sb.append("    customerCreditRatingStateRetrieveActionResponse: ").append(toIndentedString(customerCreditRatingStateRetrieveActionResponse)).append("\n");
    sb.append("    customerCreditRatingStateInstanceReportRecord: ").append(toIndentedString(customerCreditRatingStateInstanceReportRecord)).append("\n");
    sb.append("    customerCreditRatingStateInstanceAnalysis: ").append(toIndentedString(customerCreditRatingStateInstanceAnalysis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
