/*
 * Customer Credit Rating
 * This service domain maintains and administers the bank's credit assessment for customers.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customercreditrating.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CRCustomerCreditRatingStateRequestInputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-03T16:36:13.702891+02:00[Europe/Madrid]")
public class CRCustomerCreditRatingStateRequestInputModel {
  @SerializedName("customerCreditRatingServicingSessionReference")
  private String customerCreditRatingServicingSessionReference = null;

  @SerializedName("customerCreditRatingStateInstanceReference")
  private String customerCreditRatingStateInstanceReference = null;

  @SerializedName("customerCreditRatingStateInstanceRecord")
  private Object customerCreditRatingStateInstanceRecord = null;

  @SerializedName("customerCreditRatingStateRequestActionTaskRecord")
  private Object customerCreditRatingStateRequestActionTaskRecord = null;

  @SerializedName("requestRecordType")
  private Object requestRecordType = null;

  public CRCustomerCreditRatingStateRequestInputModel customerCreditRatingServicingSessionReference(String customerCreditRatingServicingSessionReference) {
    this.customerCreditRatingServicingSessionReference = customerCreditRatingServicingSessionReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the active servicing session 
   * @return customerCreditRatingServicingSessionReference
  **/
  @Schema(example = "CCRSSR701755", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the active servicing session ")
  public String getCustomerCreditRatingServicingSessionReference() {
    return customerCreditRatingServicingSessionReference;
  }

  public void setCustomerCreditRatingServicingSessionReference(String customerCreditRatingServicingSessionReference) {
    this.customerCreditRatingServicingSessionReference = customerCreditRatingServicingSessionReference;
  }

  public CRCustomerCreditRatingStateRequestInputModel customerCreditRatingStateInstanceReference(String customerCreditRatingStateInstanceReference) {
    this.customerCreditRatingStateInstanceReference = customerCreditRatingStateInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Customer Credit Rating State instance 
   * @return customerCreditRatingStateInstanceReference
  **/
  @Schema(example = "CCRSIR796000", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Customer Credit Rating State instance ")
  public String getCustomerCreditRatingStateInstanceReference() {
    return customerCreditRatingStateInstanceReference;
  }

  public void setCustomerCreditRatingStateInstanceReference(String customerCreditRatingStateInstanceReference) {
    this.customerCreditRatingStateInstanceReference = customerCreditRatingStateInstanceReference;
  }

  public CRCustomerCreditRatingStateRequestInputModel customerCreditRatingStateInstanceRecord(Object customerCreditRatingStateInstanceRecord) {
    this.customerCreditRatingStateInstanceRecord = customerCreditRatingStateInstanceRecord;
    return this;
  }

   /**
   * Get customerCreditRatingStateInstanceRecord
   * @return customerCreditRatingStateInstanceRecord
  **/
  @Schema(description = "")
  public Object getCustomerCreditRatingStateInstanceRecord() {
    return customerCreditRatingStateInstanceRecord;
  }

  public void setCustomerCreditRatingStateInstanceRecord(Object customerCreditRatingStateInstanceRecord) {
    this.customerCreditRatingStateInstanceRecord = customerCreditRatingStateInstanceRecord;
  }

  public CRCustomerCreditRatingStateRequestInputModel customerCreditRatingStateRequestActionTaskRecord(Object customerCreditRatingStateRequestActionTaskRecord) {
    this.customerCreditRatingStateRequestActionTaskRecord = customerCreditRatingStateRequestActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The request service call consolidated processing record 
   * @return customerCreditRatingStateRequestActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The request service call consolidated processing record ")
  public Object getCustomerCreditRatingStateRequestActionTaskRecord() {
    return customerCreditRatingStateRequestActionTaskRecord;
  }

  public void setCustomerCreditRatingStateRequestActionTaskRecord(Object customerCreditRatingStateRequestActionTaskRecord) {
    this.customerCreditRatingStateRequestActionTaskRecord = customerCreditRatingStateRequestActionTaskRecord;
  }

  public CRCustomerCreditRatingStateRequestInputModel requestRecordType(Object requestRecordType) {
    this.requestRecordType = requestRecordType;
    return this;
  }

   /**
   * Get requestRecordType
   * @return requestRecordType
  **/
  @Schema(description = "")
  public Object getRequestRecordType() {
    return requestRecordType;
  }

  public void setRequestRecordType(Object requestRecordType) {
    this.requestRecordType = requestRecordType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CRCustomerCreditRatingStateRequestInputModel crCustomerCreditRatingStateRequestInputModel = (CRCustomerCreditRatingStateRequestInputModel) o;
    return Objects.equals(this.customerCreditRatingServicingSessionReference, crCustomerCreditRatingStateRequestInputModel.customerCreditRatingServicingSessionReference) &&
        Objects.equals(this.customerCreditRatingStateInstanceReference, crCustomerCreditRatingStateRequestInputModel.customerCreditRatingStateInstanceReference) &&
        Objects.equals(this.customerCreditRatingStateInstanceRecord, crCustomerCreditRatingStateRequestInputModel.customerCreditRatingStateInstanceRecord) &&
        Objects.equals(this.customerCreditRatingStateRequestActionTaskRecord, crCustomerCreditRatingStateRequestInputModel.customerCreditRatingStateRequestActionTaskRecord) &&
        Objects.equals(this.requestRecordType, crCustomerCreditRatingStateRequestInputModel.requestRecordType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerCreditRatingServicingSessionReference, customerCreditRatingStateInstanceReference, customerCreditRatingStateInstanceRecord, customerCreditRatingStateRequestActionTaskRecord, requestRecordType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CRCustomerCreditRatingStateRequestInputModel {\n");
    
    sb.append("    customerCreditRatingServicingSessionReference: ").append(toIndentedString(customerCreditRatingServicingSessionReference)).append("\n");
    sb.append("    customerCreditRatingStateInstanceReference: ").append(toIndentedString(customerCreditRatingStateInstanceReference)).append("\n");
    sb.append("    customerCreditRatingStateInstanceRecord: ").append(toIndentedString(customerCreditRatingStateInstanceRecord)).append("\n");
    sb.append("    customerCreditRatingStateRequestActionTaskRecord: ").append(toIndentedString(customerCreditRatingStateRequestActionTaskRecord)).append("\n");
    sb.append("    requestRecordType: ").append(toIndentedString(requestRecordType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
