/*
 * Customer Credit Rating
 * This service domain maintains and administers the bank's credit assessment for customers.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customercreditrating.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CRCustomerCreditRatingStateInitiateOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-03T16:36:13.702891+02:00[Europe/Madrid]")
public class CRCustomerCreditRatingStateInitiateOutputModel {
  @SerializedName("customerCreditRatingStateInstanceReference")
  private String customerCreditRatingStateInstanceReference = null;

  @SerializedName("customerCreditRatingStateInitiateActionReference")
  private String customerCreditRatingStateInitiateActionReference = null;

  @SerializedName("customerCreditRatingStateInitiateActionRecord")
  private Object customerCreditRatingStateInitiateActionRecord = null;

  @SerializedName("customerCreditRatingStateInstanceStatus")
  private String customerCreditRatingStateInstanceStatus = null;

  @SerializedName("customerCreditRatingStateInstanceRecord")
  private Object customerCreditRatingStateInstanceRecord = null;

  public CRCustomerCreditRatingStateInitiateOutputModel customerCreditRatingStateInstanceReference(String customerCreditRatingStateInstanceReference) {
    this.customerCreditRatingStateInstanceReference = customerCreditRatingStateInstanceReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Customer Credit Rating State instance 
   * @return customerCreditRatingStateInstanceReference
  **/
  @Schema(example = "CCRSIR702240", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the Customer Credit Rating State instance ")
  public String getCustomerCreditRatingStateInstanceReference() {
    return customerCreditRatingStateInstanceReference;
  }

  public void setCustomerCreditRatingStateInstanceReference(String customerCreditRatingStateInstanceReference) {
    this.customerCreditRatingStateInstanceReference = customerCreditRatingStateInstanceReference;
  }

  public CRCustomerCreditRatingStateInitiateOutputModel customerCreditRatingStateInitiateActionReference(String customerCreditRatingStateInitiateActionReference) {
    this.customerCreditRatingStateInitiateActionReference = customerCreditRatingStateInitiateActionReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to an Initiate service call 
   * @return customerCreditRatingStateInitiateActionReference
  **/
  @Schema(example = "CCRSIAR702814", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to an Initiate service call ")
  public String getCustomerCreditRatingStateInitiateActionReference() {
    return customerCreditRatingStateInitiateActionReference;
  }

  public void setCustomerCreditRatingStateInitiateActionReference(String customerCreditRatingStateInitiateActionReference) {
    this.customerCreditRatingStateInitiateActionReference = customerCreditRatingStateInitiateActionReference;
  }

  public CRCustomerCreditRatingStateInitiateOutputModel customerCreditRatingStateInitiateActionRecord(Object customerCreditRatingStateInitiateActionRecord) {
    this.customerCreditRatingStateInitiateActionRecord = customerCreditRatingStateInitiateActionRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The Initiate service call input and output record 
   * @return customerCreditRatingStateInitiateActionRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The Initiate service call input and output record ")
  public Object getCustomerCreditRatingStateInitiateActionRecord() {
    return customerCreditRatingStateInitiateActionRecord;
  }

  public void setCustomerCreditRatingStateInitiateActionRecord(Object customerCreditRatingStateInitiateActionRecord) {
    this.customerCreditRatingStateInitiateActionRecord = customerCreditRatingStateInitiateActionRecord;
  }

  public CRCustomerCreditRatingStateInitiateOutputModel customerCreditRatingStateInstanceStatus(String customerCreditRatingStateInstanceStatus) {
    this.customerCreditRatingStateInstanceStatus = customerCreditRatingStateInstanceStatus;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The status of the Customer Credit Rating State instance (e.g. initialised, pending, active) 
   * @return customerCreditRatingStateInstanceStatus
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The status of the Customer Credit Rating State instance (e.g. initialised, pending, active) ")
  public String getCustomerCreditRatingStateInstanceStatus() {
    return customerCreditRatingStateInstanceStatus;
  }

  public void setCustomerCreditRatingStateInstanceStatus(String customerCreditRatingStateInstanceStatus) {
    this.customerCreditRatingStateInstanceStatus = customerCreditRatingStateInstanceStatus;
  }

  public CRCustomerCreditRatingStateInitiateOutputModel customerCreditRatingStateInstanceRecord(Object customerCreditRatingStateInstanceRecord) {
    this.customerCreditRatingStateInstanceRecord = customerCreditRatingStateInstanceRecord;
    return this;
  }

   /**
   * Get customerCreditRatingStateInstanceRecord
   * @return customerCreditRatingStateInstanceRecord
  **/
  @Schema(description = "")
  public Object getCustomerCreditRatingStateInstanceRecord() {
    return customerCreditRatingStateInstanceRecord;
  }

  public void setCustomerCreditRatingStateInstanceRecord(Object customerCreditRatingStateInstanceRecord) {
    this.customerCreditRatingStateInstanceRecord = customerCreditRatingStateInstanceRecord;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CRCustomerCreditRatingStateInitiateOutputModel crCustomerCreditRatingStateInitiateOutputModel = (CRCustomerCreditRatingStateInitiateOutputModel) o;
    return Objects.equals(this.customerCreditRatingStateInstanceReference, crCustomerCreditRatingStateInitiateOutputModel.customerCreditRatingStateInstanceReference) &&
        Objects.equals(this.customerCreditRatingStateInitiateActionReference, crCustomerCreditRatingStateInitiateOutputModel.customerCreditRatingStateInitiateActionReference) &&
        Objects.equals(this.customerCreditRatingStateInitiateActionRecord, crCustomerCreditRatingStateInitiateOutputModel.customerCreditRatingStateInitiateActionRecord) &&
        Objects.equals(this.customerCreditRatingStateInstanceStatus, crCustomerCreditRatingStateInitiateOutputModel.customerCreditRatingStateInstanceStatus) &&
        Objects.equals(this.customerCreditRatingStateInstanceRecord, crCustomerCreditRatingStateInitiateOutputModel.customerCreditRatingStateInstanceRecord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerCreditRatingStateInstanceReference, customerCreditRatingStateInitiateActionReference, customerCreditRatingStateInitiateActionRecord, customerCreditRatingStateInstanceStatus, customerCreditRatingStateInstanceRecord);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CRCustomerCreditRatingStateInitiateOutputModel {\n");
    
    sb.append("    customerCreditRatingStateInstanceReference: ").append(toIndentedString(customerCreditRatingStateInstanceReference)).append("\n");
    sb.append("    customerCreditRatingStateInitiateActionReference: ").append(toIndentedString(customerCreditRatingStateInitiateActionReference)).append("\n");
    sb.append("    customerCreditRatingStateInitiateActionRecord: ").append(toIndentedString(customerCreditRatingStateInitiateActionRecord)).append("\n");
    sb.append("    customerCreditRatingStateInstanceStatus: ").append(toIndentedString(customerCreditRatingStateInstanceStatus)).append("\n");
    sb.append("    customerCreditRatingStateInstanceRecord: ").append(toIndentedString(customerCreditRatingStateInstanceRecord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
