/*
 * Customer Credit Rating
 * This service domain maintains and administers the bank's credit assessment for customers.
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.redhat.mercury.customercreditrating.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SDCustomerCreditRatingActivateOutputModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-06-03T15:34:54.132884+02:00[Europe/Madrid]")
public class SDCustomerCreditRatingActivateOutputModel {
  @SerializedName("serviceDomainActivationActionTaskReference")
  private String serviceDomainActivationActionTaskReference = null;

  @SerializedName("serviceDomainActivationActionTaskRecord")
  private Object serviceDomainActivationActionTaskRecord = null;

  @SerializedName("serviceDomainServicingSessionReference")
  private String serviceDomainServicingSessionReference = null;

  @SerializedName("serviceDomainServicingSessionRecord")
  private Object serviceDomainServicingSessionRecord = null;

  @SerializedName("serviceDomainServiceConfigurationRecord")
  private Object serviceDomainServiceConfigurationRecord = null;

  @SerializedName("serviceDomainServicingSessionStatus")
  private String serviceDomainServicingSessionStatus = null;

  public SDCustomerCreditRatingActivateOutputModel serviceDomainActivationActionTaskReference(String serviceDomainActivationActionTaskReference) {
    this.serviceDomainActivationActionTaskReference = serviceDomainActivationActionTaskReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a service activation service call 
   * @return serviceDomainActivationActionTaskReference
  **/
  @Schema(example = "SAATR758836", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to a service activation service call ")
  public String getServiceDomainActivationActionTaskReference() {
    return serviceDomainActivationActionTaskReference;
  }

  public void setServiceDomainActivationActionTaskReference(String serviceDomainActivationActionTaskReference) {
    this.serviceDomainActivationActionTaskReference = serviceDomainActivationActionTaskReference;
  }

  public SDCustomerCreditRatingActivateOutputModel serviceDomainActivationActionTaskRecord(Object serviceDomainActivationActionTaskRecord) {
    this.serviceDomainActivationActionTaskRecord = serviceDomainActivationActionTaskRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The activation service call consolidated processing record 
   * @return serviceDomainActivationActionTaskRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: The activation service call consolidated processing record ")
  public Object getServiceDomainActivationActionTaskRecord() {
    return serviceDomainActivationActionTaskRecord;
  }

  public void setServiceDomainActivationActionTaskRecord(Object serviceDomainActivationActionTaskRecord) {
    this.serviceDomainActivationActionTaskRecord = serviceDomainActivationActionTaskRecord;
  }

  public SDCustomerCreditRatingActivateOutputModel serviceDomainServicingSessionReference(String serviceDomainServicingSessionReference) {
    this.serviceDomainServicingSessionReference = serviceDomainServicingSessionReference;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the active servicing session 
   * @return serviceDomainServicingSessionReference
  **/
  @Schema(example = "SSSR783215", description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Reference to the active servicing session ")
  public String getServiceDomainServicingSessionReference() {
    return serviceDomainServicingSessionReference;
  }

  public void setServiceDomainServicingSessionReference(String serviceDomainServicingSessionReference) {
    this.serviceDomainServicingSessionReference = serviceDomainServicingSessionReference;
  }

  public SDCustomerCreditRatingActivateOutputModel serviceDomainServicingSessionRecord(Object serviceDomainServicingSessionRecord) {
    this.serviceDomainServicingSessionRecord = serviceDomainServicingSessionRecord;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: Consolidated information record for the servicing session 
   * @return serviceDomainServicingSessionRecord
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Binary  general-info: Consolidated information record for the servicing session ")
  public Object getServiceDomainServicingSessionRecord() {
    return serviceDomainServicingSessionRecord;
  }

  public void setServiceDomainServicingSessionRecord(Object serviceDomainServicingSessionRecord) {
    this.serviceDomainServicingSessionRecord = serviceDomainServicingSessionRecord;
  }

  public SDCustomerCreditRatingActivateOutputModel serviceDomainServiceConfigurationRecord(Object serviceDomainServiceConfigurationRecord) {
    this.serviceDomainServiceConfigurationRecord = serviceDomainServiceConfigurationRecord;
    return this;
  }

   /**
   * Get serviceDomainServiceConfigurationRecord
   * @return serviceDomainServiceConfigurationRecord
  **/
  @Schema(description = "")
  public Object getServiceDomainServiceConfigurationRecord() {
    return serviceDomainServiceConfigurationRecord;
  }

  public void setServiceDomainServiceConfigurationRecord(Object serviceDomainServiceConfigurationRecord) {
    this.serviceDomainServiceConfigurationRecord = serviceDomainServiceConfigurationRecord;
  }

  public SDCustomerCreditRatingActivateOutputModel serviceDomainServicingSessionStatus(String serviceDomainServicingSessionStatus) {
    this.serviceDomainServicingSessionStatus = serviceDomainServicingSessionStatus;
    return this;
  }

   /**
   * &#x60;status: Not Mapped&#x60;  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The current operating status of the overall servicing session 
   * @return serviceDomainServicingSessionStatus
  **/
  @Schema(description = "`status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The current operating status of the overall servicing session ")
  public String getServiceDomainServicingSessionStatus() {
    return serviceDomainServicingSessionStatus;
  }

  public void setServiceDomainServicingSessionStatus(String serviceDomainServicingSessionStatus) {
    this.serviceDomainServicingSessionStatus = serviceDomainServicingSessionStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDCustomerCreditRatingActivateOutputModel sdCustomerCreditRatingActivateOutputModel = (SDCustomerCreditRatingActivateOutputModel) o;
    return Objects.equals(this.serviceDomainActivationActionTaskReference, sdCustomerCreditRatingActivateOutputModel.serviceDomainActivationActionTaskReference) &&
        Objects.equals(this.serviceDomainActivationActionTaskRecord, sdCustomerCreditRatingActivateOutputModel.serviceDomainActivationActionTaskRecord) &&
        Objects.equals(this.serviceDomainServicingSessionReference, sdCustomerCreditRatingActivateOutputModel.serviceDomainServicingSessionReference) &&
        Objects.equals(this.serviceDomainServicingSessionRecord, sdCustomerCreditRatingActivateOutputModel.serviceDomainServicingSessionRecord) &&
        Objects.equals(this.serviceDomainServiceConfigurationRecord, sdCustomerCreditRatingActivateOutputModel.serviceDomainServiceConfigurationRecord) &&
        Objects.equals(this.serviceDomainServicingSessionStatus, sdCustomerCreditRatingActivateOutputModel.serviceDomainServicingSessionStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceDomainActivationActionTaskReference, serviceDomainActivationActionTaskRecord, serviceDomainServicingSessionReference, serviceDomainServicingSessionRecord, serviceDomainServiceConfigurationRecord, serviceDomainServicingSessionStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDCustomerCreditRatingActivateOutputModel {\n");
    
    sb.append("    serviceDomainActivationActionTaskReference: ").append(toIndentedString(serviceDomainActivationActionTaskReference)).append("\n");
    sb.append("    serviceDomainActivationActionTaskRecord: ").append(toIndentedString(serviceDomainActivationActionTaskRecord)).append("\n");
    sb.append("    serviceDomainServicingSessionReference: ").append(toIndentedString(serviceDomainServicingSessionReference)).append("\n");
    sb.append("    serviceDomainServicingSessionRecord: ").append(toIndentedString(serviceDomainServicingSessionRecord)).append("\n");
    sb.append("    serviceDomainServiceConfigurationRecord: ").append(toIndentedString(serviceDomainServiceConfigurationRecord)).append("\n");
    sb.append("    serviceDomainServicingSessionStatus: ").append(toIndentedString(serviceDomainServicingSessionStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
