apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: quarkus-native-build
spec:
  params:
    - name: SUBDIRECTORY
      type: string
    - name: DOCKERFILE
      type: string
    - name: IMAGE
      type: string
  steps:
    - image: bash:latest
      name: organize-folders
      script: |
        #!/usr/bin/env bash
        root=$(echo "$(params.SUBDIRECTORY)" | cut -d/ -f1)
        if [ -d "src" ]
        then
          rm -rf src pom.xml target
        fi
        mv -f $(params.SUBDIRECTORY)/$(params.SUBDIRECTORY)/* .
        rm -rf $root
        if [ ! -d "/home/kogito/.m2/repository" ]
        then
          mkdir /home/kogito/.m2/repository
        fi
      workingDir: $(workspaces.source.path)
    - name: compile-quarkus-native-binary
      image: quay.io/kiegroup/kogito-builder:1.7
      imagePullPolicy: IfNotPresent
      workingDir: /build
      command:
        - /usr/share/maven/bin/mvn
      args:
        - package
      securityContext:
        privileged: true
    - name: build-and-push-container-image
      image: registry.redhat.io/ubi8/buildah:8.4
      imagePullPolicy: IfNotPresent
      script: |
        #!/usr/bin/env bash
        set -e
        ls -la /build
        buildah bud --storage-driver vfs --squash -f $(params.DOCKERFILE) -t "$(params.IMAGE)" .
        buildah push --storage-driver vfs --tls-verify=false "$(params.IMAGE)"
      workingDir: $(workspaces.source.path)
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
  workspaces:
    - name: source
      mountPath: /build
    - name: maven-cache
      mountPath: /home/kogito/.m2
  volumes:
    - name: varlibcontainers
      emptyDir: {}