apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: businessautomation-operator
  namespace: mercury-common
  labels:
    operators.coreos.com/businessautomation-operator.mercury-common: ""
spec:
  channel: stable
  installPlanApproval: Automatic
  name: businessautomation-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: businessautomation-operator.7.11.1-1