---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: mercury-operator
  name: mercury-operator
  namespace: mercury
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mercury-operator-cluster-role
  namespace: mercury
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
      - mercury.redhat.io
      - kafka.strimzi.io
      - camel.apache.org
    resources:
      - servicedomainclusters
      - servicedomainclusters/status
      - servicedomains
      - servicedomains/status
      - kafkas
      - kafkatopics
      - kafkausers
      - integrations
      - services
      - deployments
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mercury-operator-cluster-role-binding
  namespace: mercury
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: mercury-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: mercury-operator
    namespace: mercury
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mercury-operator-role
  namespace: mercury
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mercury-operator-role-binding
  namespace: mercury
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: mercury-operator-role
subjects:
  - kind: ServiceAccount
    name: mercury-operator
    namespace: mercury
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mercury-operator
  name: mercury-operator
  namespace: mercury
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mercury-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mercury-operator
      namespace: mercury
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/ecosystem-appeng/mercury-operator:1.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
          name: mercury-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
      serviceAccount: mercury-operator
