apiVersion: v1
kind: ConfigMap
metadata:
  name: my-sd-cluster-config
data:
  kafka.bootstrap.servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-offer-http-route
  labels:
    app: customer-offer-http-route
    service-domain: customer-offer
spec:
  selector:
    matchLabels:
      app: customer-offer-http-route
  template:
    metadata:
      labels:
        app: customer-offer-http-route
        service-domain: customer-offer
    spec:
      containers:
        - name: container
          image: quay.io/ecosystem-appeng/customer-offer-integration-camel-rest:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-offer
  labels:
    app: bian-customer-offer
    service-domain: customer-offer
spec:
  selector:
    matchLabels:
      app: bian-customer-offer
  template:
    metadata:
      labels:
        app: bian-customer-offer
        service-domain: customer-offer
    spec:
      containers:
        - name: business-service
          image: quay.io/ecosystem-appeng/customer-offer-example:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: grpc
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: my-sd-cluster-config
                  key: kafka.bootstrap.servers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: party-routing-profile
  labels:
    app: bian-party-routing-profile
    service-domain: party-routing-profile
spec:
  selector:
    matchLabels:
      app: bian-party-routing-profile
  template:
    metadata:
      labels:
        app: bian-party-routing-profile
        service-domain: party-routing-profile
    spec:
      containers:
        - name: business-service
          image: quay.io/ecosystem-appeng/party-routing-profile-example:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: grpc
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: my-sd-cluster-config
                  key: kafka.bootstrap.servers
---
apiVersion: v1
kind: Service
metadata:
  name: customer-offer-http-route
  labels:
    app: customer-offer-http-route
    service-domain: customer-offer
    mercury-binding: external
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: customer-offer-http-route
---
apiVersion: v1
kind: Service
metadata:
  name: customer-offer
  labels:
    app: bian-customer-offer
    service-domain: customer-offer
    mercury-binding: internal
spec:
  ports:
    - port: 9000
      protocol: TCP
      name: grpc
  selector:
    app: bian-customer-offer
---
apiVersion: v1
kind: Service
metadata:
  name: party-routing-profile
  labels:
    app: bian-party-routing-profile
    service-domain: party-routing-profile
    mercury-binding: internal
spec:
  ports:
    - port: 9000
      protocol: TCP
      name: grpc
  selector:
    app: bian-party-routing-profile
