apiVersion: v1
kind: ConfigMap
metadata:
  name: my-sd-cluster-config
data:
  kafka.bootstrap.servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-offer
  labels:
    app: bian-customer-offer
    service-domain: customer-offer
spec:
  selector:
    matchLabels:
      app: bian-customer-offer
  template:
    metadata:
      labels:
        app: bian-customer-offer
        service-domain: customer-offer
    spec:
      serviceAccountName: bian-binding-service-sa
      containers:
        - name: business-service
          image: quay.io/ecosystem-appeng/customer-offer-kogito-example:1.0.0-SNAPSHOT
          ports:
            - containerPort: 10001
              name: inbound
            - containerPort: 8080
              name: http
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: my-sd-cluster-config
                  key: kafka.bootstrap.servers
---
apiVersion: v1
kind: Service
metadata:
  name: customer-offer-internal
  labels:
    app: bian-customer-offer
    service-domain: customer-offer
    mercury-binding: internal
spec:
  ports:
    - port: 10101
      protocol: TCP
      name: internal
  selector:
    app: bian-customer-offer
---
apiVersion: v1
kind: Service
metadata:
  name: customer-offer-http
  labels:
    app: bian-customer-offer
    service-domain: customer-offer
    mercury-binding: external
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: bian-customer-offer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: party-routing-profile
  labels:
    app: bian-party-routing-profile
    service-domain: party-routing-profile
spec:
  selector:
    matchLabels:
      app: bian-party-routing-profile
  template:
    metadata:
      labels:
        app: bian-party-routing-profile
        service-domain: party-routing-profile
    spec:
      serviceAccountName: bian-binding-service-sa
      containers:
        - name: business-service
          image: quay.io/ecosystem-appeng/party-routing-profile-example:1.0.0-SNAPSHOT
          ports:
            - containerPort: 10001
              name: inbound
            - containerPort: 8080
              name: http
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: my-sd-cluster-config
                  key: kafka.bootstrap.servers
---
apiVersion: v1
kind: Service
metadata:
  name: party-routing-profile-internal
  labels:
    app: bian-party-routing-profile
    service-domain: party-routing-profile
    mercury-binding: internal
spec:
  ports:
    - port: 10101
      protocol: TCP
      name: internal
  selector:
    app: bian-party-routing-profile
---
apiVersion: v1
kind: Service
metadata:
  name: party-routing-profile-http
  labels:
    app: bian-party-routing-profile
    service-domain: party-routing-profile
    mercury-binding: external
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: bian-party-routing-profile