apiVersion: mercury.redhat.io/v1alpha1
kind: ServiceDomain
metadata:
  name: example-customer-credit-rating
  labels:
    service-domain: customer-credit-rating
spec:
  businessImage: quay.io/ecosystem-appeng/customer-credit-rating-example:1.0.1-SNAPSHOT
  serviceDomainInfra: service-domain-infra
  type: CustomerCreditRating
  expose:
    - http