apiVersion: v1
kind: Service
metadata:
  name: customer-offer-reporting
  labels:
    app: customer-offer-reporting
    service-domain: customer-offer
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: bian-example-customer-offer